export interface FAQ {
  q: string;
  a: string;
}

export interface Post {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: string;
  category: string;
  faq?: FAQ[];
  titleEn?: string;
  descriptionEn?: string;
  categoryEn?: string;
  readTimeEn?: string;
  faqEn?: FAQ[];
}

export const POSTS: Post[] = [
  {
    slug: "reklamacja-kaufland",
    title: "Reklamacja w Kaufland: elektronika z oferty tygodnia i lada mięsna (2026)",
    description: "Kaufland twierdzi, że grill z oferty tygodnia to towar sezonowy? Nieprawda — masz 2 lata na reklamację. Jak reklamować mięso i pieczywo kupione na wagę.",
    date: "2026-08-06",
    readTime: "6 min",
    category: "Sklep stacjonarny",
    titleEn: "Complaint at Kaufland: Weekly-Offer Electronics and the Meat Counter (2026)",
    descriptionEn: "Kaufland says a weekly-offer grill is seasonal, no complaints allowed? Not true — you get 2 years. How to complain about meat and bread bought by weight.",
    categoryEn: "Physical Store",
    readTimeEn: "6 min",
    faq: [
      { q: "Kaufland mówi że grill/basen to towar sezonowy i po sezonie nie przyjmują reklamacji. Czy to prawda?", a: "Nie. Sezonowość produktu nie ma znaczenia dla ustawowego terminu reklamacji. Masz 2 lata od daty zakupu (art. 43c ust. 1 UPK), niezależnie od pory roku czy tego, czy sklep nadal sprzedaje dany model." },
      { q: "Kupiłem mięso na wagę w Kauflandzie i było nieświeże mimo ważnej daty przydatności. Czy mogę reklamować?", a: "Tak. To niezgodność towaru z umową na podstawie art. 43b UPK. Zachowaj resztki produktu oraz etykietę wagową jako dowód i zgłoś reklamację z paragonem lub e-paragonem z aplikacji Kaufland Card. Przy podejrzeniu zagrożenia zdrowia zgłoś sprawę też do Sanepidu." },
      { q: "Produkt z oferty tygodnia nie jest już dostępny w Kauflandzie. Czy mogą odmówić reklamacji?", a: "Nie. Jeśli wymiana na identyczny egzemplarz jest niemożliwa, przysługuje Ci obniżenie ceny lub pełny zwrot pieniędzy (art. 43e ust. 1 UPK). Brak towaru w bieżącym asortymencie to podstawa do zwrotu, a nie odmowy." },
      { q: "Kasjer zaproponował mi płatną gwarancję rozszerzoną przy kasie, a ja odmówiłem. Czy zostałem bez ochrony?", a: "Nie. Płatna gwarancja rozszerzona to osobna, dobrowolna umowa z zewnętrznym ubezpieczycielem. Twoje ustawowe prawo do reklamacji z tytułu niezgodności towaru z umową działa niezależnie od niej i obowiązuje przez pełne 2 lata." },
    ],
    faqEn: [
      { q: "Kaufland says a grill/pool is a seasonal item and won't accept complaints after the season. Is that true?", a: "No. Product seasonality has no bearing on the statutory complaint period. You have 2 years from the date of purchase (Art. 43c §1 CRA), regardless of the time of year or whether the store still sells that model." },
      { q: "I bought meat by weight at Kaufland and it was stale despite being within its use-by date. Can I complain?", a: "Yes. That is non-conformity under Art. 43b CRA. Keep the remains of the product and the weight label as evidence, and file the complaint with your receipt or e-receipt from the Kaufland Card app. If you suspect a health risk, also report it to the Sanitary Inspectorate." },
      { q: "The weekly-offer product is no longer available at Kaufland. Can they refuse my complaint?", a: "No. If replacement with an identical item is impossible, you are entitled to a price reduction or a full refund (Art. 43e §1 CRA). The item being out of the current range is grounds for a refund, not for refusal." },
      { q: "The cashier offered me a paid extended warranty at checkout and I declined. Am I left without protection?", a: "No. A paid extended warranty is a separate, voluntary contract with a third-party insurer. Your statutory right to complain about non-conformity applies independently of it and lasts the full 2 years." },
    ],
  },
  {
    slug: "reklamacja-wycieczki",
    title: "Reklamacja wycieczki: hotel niezgodny z opisem i zmarnowany urlop (2026)",
    description: "Hotel z katalogu nie zgadza się z rzeczywistością? Masz prawo do obniżki ceny i zadośćuczynienia za zmarnowany urlop. 3 lata na reklamację, nie 30 dni.",
    date: "2026-08-03",
    readTime: "6 min",
    category: "Turystyka",
    faq: [
      { q: "Czy mogę żądać zadośćuczynienia za „zmarnowany urlop”, jeśli hotel po prostu nie odpowiadał opisowi?", a: "Tak, jeśli niezgodność była na tyle istotna, że realnie pozbawiła Cię przyjemności z wypoczynku — np. cały pobyt bez obiecanego basenu czy hałas z budowy przez większość doby. Drobne niedogodności zwykle uzasadniają tylko obniżkę ceny (art. 50 ust. 1), a nie zadośćuczynienie (art. 50 ust. 2) — decyduje skala i wpływ na cały wyjazd." },
      { q: "Kupiłem wycieczkę przez lokalne biuro podróży odsprzedające ofertę dużego touroperatora. Do kogo składam reklamację?", a: "Możesz skierować pismo do agenta turystycznego, u którego kupiłeś wycieczkę — art. 51 ustawy o imprezach turystycznych nakazuje mu niezwłocznie przekazać żądanie organizatorowi. Możesz też napisać bezpośrednio do organizatora, który odpowiada za realizację imprezy." },
      { q: "Organizator zaproponował mi voucher na kolejny wyjazd zamiast zwrotu pieniędzy. Czy muszę się zgodzić?", a: "Nie. Voucher to propozycja handlowa, nie obowiązek. Na podstawie art. 50 ustawy o imprezach turystycznych masz prawo żądać obniżki ceny lub odszkodowania w pieniądzu." },
      { q: "Ile czasu mam na reklamację niezgodności wycieczki?", a: "3 lata od zakończenia imprezy turystycznej (art. 50 ust. 4 ustawy o imprezach turystycznych). Stary 30-dniowy termin zniesiono w 2018 roku — ale uwaga, zniesiono też automatyczne uznanie reklamacji przy braku odpowiedzi organizatora." },
    ],
  },
  {
    slug: "reklamacja-pepco",
    title: "Reklamacja w Pepco: prawa konsumenta niezależnie od ceny (2026)",
    description: "Kasjerka w Pepco twierdzi że przy tej cenie nie ma co reklamować? Nieprawda. Art. 43b UPK chroni Cię tak samo przy zakupie za 39 zł jak za 3 900 zł. 2 lata na reklamację, 14 dni na odpowiedź.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Sklep stacjonarny",
    faq: [
      { q: "Czy mogę reklamować towar z Pepco bez paragonu?", a: "Tak. Wystarczy wyciąg z konta bankowego, potwierdzenie płatności BLIK, zeznanie świadka lub zdjęcie paragonu. Pepco nie może odmówić reklamacji tylko dlatego, że nie masz paragonu." },
      { q: "Pepco twierdzi że przy tej cenie to normalne że się zepsuło. Czy mają rację?", a: "Nie. Art. 43b UPK nie rozróżnia towarów tanich i drogich. Czajnik za 39 zł musi działać tak, jak można tego rozsądnie oczekiwać." },
      { q: "Ile dni ma Pepco na odpowiedź na reklamację?", a: "14 dni kalendarzowych. Brak odpowiedzi = reklamacja uznana z mocy prawa (art. 7a UPK)." },
      { q: "Pepco mówi że minęło 30 dni i nie przyjmują reklamacji. Czy to prawda?", a: "Nie. Regulamin sklepu nie może skracać ustawowych 2 lat. Zapis wewnętrzny Pepco ograniczający termin jest bezskuteczny wobec konsumenta (art. 43j UPK)." },
    ],
  },
  {
    slug: "reklamacja-action",
    title: "Reklamacja w Action: jak skutecznie dochodzić praw (2026)",
    description: "Action twierdzi że produkt nie jest profesjonalny i nie podlega reklamacji? Każdy towar kupiony od przedsiębiorcy musi być zgodny z umową. 2 lata na reklamację, 14 dni na odpowiedź.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Sklep stacjonarny",
    faq: [
      { q: "Action mówi że produkt nie jest profesjonalny więc nie podlega reklamacji. Czy to prawda?", a: "Nie. Nawet produkt domowy musi działać zgodnie z rozsądnymi oczekiwaniami (art. 43b ust. 1 pkt 2 UPK). Segment cenowy nie zwalnia sprzedawcy z odpowiedzialności." },
      { q: "Action odsyła mnie do producenta. Czy muszę się do niego zwracać?", a: "Nie. Twoja umowa jest z Action, nie z producentem. Art. 43b UPK: to sprzedawca odpowiada za niezgodność towaru z umową." },
      { q: "Action nie ma tego produktu na stanie. Czy mogą odmówić reklamacji?", a: "Nie. Jeśli wymiana jest niemożliwa, masz prawo do obniżenia ceny lub odstąpienia od umowy (art. 43e ust. 1 UPK)." },
      { q: "Ile czasu mam na reklamację w Action?", a: "2 lata od daty otrzymania towaru. 14 dni na odpowiedź — brak odpowiedzi to uznanie reklamacji z mocy prawa." },
    ],
  },
  {
    slug: "reklamacja-apart",
    title: "Reklamacja biżuterii w Apart: zmiana koloru, pęknięcie, wypadnięcie kamienia (2026)",
    description: "Apart twierdzi że zmiana koloru pierścionka to naturalna patyna? Pierścionek za 1 200 zł nie powinien ciemnieć po kilku tygodniach. Art. 43b UPK: 2 lata na reklamację biżuterii.",
    date: "2026-08-02",
    readTime: "6 min",
    category: "Biżuteria",
    faq: [
      { q: "Pierścionek z Apart zmienił kolor po kilku tygodniach. Czy mogę reklamować?", a: "Tak. Szybkie ciemnienie biżuterii sprzedawanej jako rodowana to niezgodność z umową. Naturalna oksydacja srebra to proces wielomiesięczny, nie kilkutygodniowy." },
      { q: "Kamień wypadł z pierścionka Apart. Czy to wada?", a: "Tak. Kamień wypadający z oprawy po normalnym użytkowaniu to wada produkcyjna. Apart musi obalić domniemanie wady ekspertyzą (art. 43c ust. 1 UPK)." },
      { q: "Biżuteria z Apart ma grawer. Czy mogę ją reklamować?", a: "Tak. Grawer ogranicza prawo do zwrotu bez przyczyny (art. 38 pkt 3 UPK), ale nie wyłącza reklamacji z tytułu wady." },
      { q: "Apart daje tylko 30 dni na reklamację z dowodem zakupu. Czy to legalne?", a: "Nie. Regulamin Apart nie może ograniczać ustawowych 2 lat. Dowód zakupu to nie tylko paragon — wystarczy wyciąg z konta." },
    ],
  },
  {
    slug: "reklamacja-biedronka",
    title: "Reklamacja w Biedronka: elektronika Hykker, Silvercrest i inne (2026)",
    description: "Kasjerka w Biedronka twierdzi że elektronika z Biedronki nie podlega reklamacji? Nieprawda. Biedronka sprzedała Ci ten produkt i odpowiada za jego zgodność z umową. Jak złożyć reklamację krok po kroku.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Sklep stacjonarny",
    faq: [
      { q: "Biedronka mówi żebym kontaktował się z producentem Silvercrest. Czy muszę?", a: "Nie. Art. 43b UPK: to sprzedawca (Biedronka/Jeronimo Martins) odpowiada za niezgodność towaru z umową, nie producent." },
      { q: "Produkt był z oferty promocyjnej/limitowanej. Czy mogę reklamować?", a: "Tak. Cena promocyjna ani oferta limitowana nie wyłączają prawa do reklamacji. Art. 43b UPK nie zawiera wyjątku dla towarów przecenionych." },
      { q: "Czy Biedronka Home ma inne zasady reklamacji niż zwykła Biedronka?", a: "Nie. Biedronka Home to ten sam sprzedawca (Jeronimo Martins Polska S.A.). Te same przepisy, terminy i odpowiedzialność." },
      { q: "Ile czasu mam na reklamację w Biedronka?", a: "2 lata od daty zakupu. Biedronka ma 14 dni na odpowiedź — brak odpowiedzi to uznanie reklamacji z mocy prawa." },
    ],
  },
  {
    slug: "reklamacja-home-you",
    title: "Reklamacja w home&you: meble, tekstylia, dekoracje (2026)",
    description: "Mebel z home&you przyszedł zarysowany, a sklep proponuje voucher? Masz prawo do wymiany lub zwrotu pieniędzy. Koszty transportu wadliwego mebla ponosi sprzedawca. Krok po kroku.",
    date: "2026-08-02",
    readTime: "6 min",
    category: "Dom i wnętrze",
    faq: [
      { q: "home&you proponuje voucher zamiast wymiany. Czy muszę go przyjąć?", a: "Nie. Voucher to propozycja, nie rozwiązanie. Na podstawie art. 43d ust. 1 UPK masz prawo żądać naprawy lub wymiany na egzemplarz wolny od wad." },
      { q: "home&you twierdzi że zarysowanie to cecha naturalna drewna. Czy mają rację?", a: "Drobne różnice w rysunku drewna to cecha naturalna. Głębokie zarysowanie widoczne gołym okiem — nie. Mebel dekoracyjny musi wyglądać zgodnie z rozsądnymi oczekiwaniami." },
      { q: "home&you każe odesłać mebel na mój koszt. Czy muszę?", a: "Nie. Koszty związane z reklamacją (w tym transport) ponosi sprzedawca (art. 43d ust. 4 UPK). Przy dużych meblach home&you powinno zorganizować odbiór kurierem." },
      { q: "Kupiłam na homeandyou.pl. Czy mogę po prostu zwrócić towar?", a: "Tak. Przy zakupie online masz 14 dni na zwrot bez podania przyczyny (art. 27 UPK). Niezależnie od tego, reklamacja z tytułu wady to 2 lata." },
    ],
  },
  {
    slug: "reklamacja-amazon",
    title: "Reklamacja na Amazon.pl: prawa konsumenta i jak złożyć (2026)",
    description: "Amazon odmawia reklamacji lub proponuje tylko zwrot? Masz 2 lata na reklamację z tytułu niezgodności z umową. Marketplace vs Amazon jako sprzedawca — różnice i jak dochodzić praw.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Sklep internetowy",
    faq: [
      { q: "Kupiłem na Amazon od sprzedawcy marketplace. Do kogo składam reklamację?", a: "Do sprzedawcy marketplace — to on zawarł z Tobą umowę. Dane sprzedawcy znajdziesz w potwierdzeniu zamówienia. Amazon pośredniczy, ale za towar odpowiada sprzedawca." },
      { q: "Amazon proponuje zwrot zamiast wymiany. Czy muszę się zgodzić?", a: "Nie. Na podstawie art. 43d UPK masz prawo żądać naprawy lub wymiany. Zwrot to ostateczność — gdy wymiana/naprawa jest niemożliwa lub nadmiernie kosztowna." },
      { q: "Ile czasu mam na reklamację towaru z Amazon?", a: "2 lata od daty otrzymania towaru. Amazon ma 14 dni na odpowiedź — brak odpowiedzi to uznanie reklamacji z mocy prawa." },
      { q: "Towar z Amazon przyszedł uszkodzony. Co zrobić?", a: "Zrób zdjęcia uszkodzenia i opakowania. Złóż reklamację przez konto Amazon lub bezpośrednio do sprzedawcy. Uszkodzenie w transporcie to odpowiedzialność sprzedawcy, nie kuriera." },
    ],
  },
  {
    slug: "reklamacja-ikea",
    title: "Reklamacja w IKEA: meble, kuchnie, akcesoria — prawa i wzór pisma (2026)",
    description: "Mebel z IKEA ma wadę fabryczną? IKEA oferuje 365 dni na zwrot, ale Twoje ustawowe prawa to 2 lata na reklamację. Jak złożyć skuteczne pismo krok po kroku.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Dom i wnętrze",
    faq: [
      { q: "IKEA daje 365 dni na zwrot. Czy po tym terminie mogę jeszcze reklamować?", a: "Tak. 365-dniowy zwrot to polityka IKEA, nie ustawowe prawo. Reklamacja z tytułu niezgodności z umową to 2 lata od daty zakupu (art. 43c ust. 1 UPK)." },
      { q: "Mebel z IKEA się rozpadł po złożeniu zgodnie z instrukcją. Czy to wada?", a: "Tak. Jeśli złożyłeś mebel zgodnie z instrukcją, a mimo to się rozpadł, to niezgodność z umową. IKEA musi udowodnić że wada to Twoja wina." },
      { q: "Czy muszę dostarczyć duży mebel do IKEA podczas reklamacji?", a: "Nie. Przy dużych meblach IKEA powinna zorganizować odbiór na swój koszt (art. 43d ust. 4 UPK)." },
      { q: "Kupiłem kuchnię na wymiar w IKEA. Czy mogę reklamować wady montażu?", a: "Tak. Jeśli IKEA wykonywała montaż, odpowiada za jego jakość. Wady montażu to niezgodność z umową." },
    ],
  },
  {
    slug: "reklamacja-shein",
    title: "Reklamacja na SHEIN: jak dochodzić praw przy zakupach z Chin (2026)",
    description: "Towar z SHEIN nie odpowiada opisowi, ma wady lub nie dotarł? Masz prawo do reklamacji mimo że sprzedawca jest za granicą. Jak złożyć skuteczne pismo i jakie masz opcje.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Sklep internetowy",
    faq: [
      { q: "SHEIN ma siedzibę za granicą. Czy polskie prawo mnie chroni?", a: "Tak. Jeśli SHEIN kieruje ofertę do polskich konsumentów (polska wersja strony, ceny w PLN), stosuje się polskie prawo konsumenckie na podstawie art. 6 ust. 1 rozporządzenia Rzym I." },
      { q: "Ile dni mam na zwrot towaru z SHEIN?", a: "14 dni od otrzymania przesyłki na podstawie art. 27 UPK (zakup online). SHEIN oferuje też własne okno zwrotowe — sprawdź regulamin, może być dłuższe." },
      { q: "Towar z SHEIN nie odpowiada zdjęciom na stronie. Co mogę zrobić?", a: "To niezgodność z umową. Zrób zdjęcia porównawcze i złóż reklamację przez formularz SHEIN lub pisemnie." },
      { q: "SHEIN nie odpowiada na reklamację. Jakie mam opcje?", a: "Złóż chargeback przez bank/kartę. Możesz też zgłosić sprawę do Europejskiego Centrum Konsumenckiego lub Rzecznika Praw Konsumentów." },
    ],
  },
  {
    slug: "reklamacja-temu",
    title: "Reklamacja na Temu: prawa konsumenta przy zakupach z platformy (2026)",
    description: "Towar z Temu jest wadliwy, niezgodny z opisem lub nie dotarł? Mimo zagranicznego sprzedawcy masz prawa konsumenckie. Jak złożyć reklamację i odzyskać pieniądze.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Sklep internetowy",
    faq: [
      { q: "Temu to platforma chińska. Czy mogę reklamować towar?", a: "Tak. Temu kieruje ofertę do polskich konsumentów, więc stosuje się polskie prawo konsumenckie. Możesz żądać zwrotu, wymiany lub obniżenia ceny." },
      { q: "Towar z Temu nie dotarł. Co zrobić?", a: "Złóż reklamację przez aplikację Temu. Jeśli brak odpowiedzi — złóż chargeback w banku. Sprzedawca odpowiada za dostarczenie towaru." },
      { q: "Temu proponuje częściowy zwrot zamiast pełnego. Czy muszę się zgodzić?", a: "Nie. Jeśli towar jest wadliwy lub niezgodny z umową, masz prawo do pełnego zwrotu pieniędzy po odstąpieniu od umowy." },
      { q: "Jak najskuteczniej odzyskać pieniądze z Temu?", a: "Chargeback przez bank lub PayPal to najskuteczniejsza droga. Złóż reklamację w Temu, a jeśli nie rozwiążą sprawy w 14 dni — zgłoś chargeback." },
    ],
  },
  {
    slug: "reklamacja-leroy-merlin",
    title: "Reklamacja w Leroy Merlin: materiały budowlane, narzędzia, ogród (2026)",
    description: "Produkt z Leroy Merlin jest wadliwy? Masz 2 lata na reklamację niezależnie od gwarancji producenta. Jak złożyć reklamację na materiały budowlane, narzędzia i artykuły ogrodowe.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Dom i wnętrze",
    faq: [
      { q: "Leroy Merlin odsyła mnie do producenta narzędzia. Czy muszę?", a: "Nie. Art. 43b UPK: to sprzedawca (Leroy Merlin) odpowiada za niezgodność towaru z umową, nie producent." },
      { q: "Farba z Leroy Merlin ma inny kolor niż na próbniku. Czy to reklamacja?", a: "Tak, jeśli różnica jest znacząca. Próbnik koloru to część opisu towaru. Farba powinna odpowiadać wybranej próbce." },
      { q: "Kupiłem materiały budowlane i okazały się wadliwe po montażu. Czy mogę żądać pokrycia kosztów demontażu?", a: "Tak. Art. 43d ust. 4 UPK: sprzedawca ponosi koszty związane z reklamacją, w tym koszty demontażu i ponownego montażu." },
      { q: "Ile czasu na reklamację w Leroy Merlin?", a: "2 lata od daty otrzymania towaru. 14 dni na odpowiedź — brak odpowiedzi = reklamacja uznana." },
    ],
  },
  {
    slug: "reklamacja-morele",
    title: "Reklamacja w Morele.net: elektronika, komputery, podzespoły (2026)",
    description: "Sprzęt z Morele.net jest wadliwy? Masz 2 lata na reklamację z tytułu niezgodności z umową — niezależnie od gwarancji producenta. Jak złożyć reklamację krok po kroku.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Elektronika",
    faq: [
      { q: "Morele.net odsyła mnie do serwisu producenta. Czy muszę?", a: "Nie. Art. 43b UPK: to sprzedawca (Morele.net) odpowiada za niezgodność towaru z umową. Gwarancja producenta to opcja dodatkowa." },
      { q: "Podzespół komputerowy z Morele jest niekompatybilny mimo opisu. Czy to reklamacja?", a: "Tak. Jeśli opis na stronie wskazywał kompatybilność, a produkt jej nie ma, to niezgodność towaru z umową." },
      { q: "Ile czasu ma Morele.net na odpowiedź na reklamację?", a: "14 dni kalendarzowych. Brak odpowiedzi = reklamacja uznana z mocy prawa (art. 7a UPK)." },
      { q: "Sprzęt z Morele zepsuł się po 13 miesiącach. Czy za późno na reklamację?", a: "Nie. Masz 2 lata od daty otrzymania towaru. 13 miesięcy to nadal w granicach ustawowego terminu." },
    ],
  },
  {
    slug: "reklamacja-hm",
    title: "Reklamacja w H&M: odzież, buty, akcesoria — prawa konsumenta (2026)",
    description: "Ubranie z H&M rozleciało się po pierwszym praniu? Masz 2 lata na reklamację. H&M nie może ograniczyć Twoich praw do 30-dniowego okna zwrotowego. Jak złożyć reklamację.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Odzież",
    faq: [
      { q: "Ubranie z H&M zniszczyło się po pierwszym praniu zgodnie z instrukcją. Czy to reklamacja?", a: "Tak. Odzież powinna wytrzymać normalne użytkowanie. Zniszczenie po praniu zgodnym z instrukcją na metce to niezgodność z umową." },
      { q: "H&M mówi że minęło 30 dni i nie przyjmują zwrotów. Czy to koniec?", a: "Nie. 30 dni to polityka zwrotów H&M. Reklamacja z tytułu wady to 2 lata (art. 43c ust. 1 UPK)." },
      { q: "Buty z H&M się rozkleiły po 2 miesiącach. Co mogę zrobić?", a: "Złóż reklamację w sklepie lub przez formularz na hm.com. Rozklajanie butów po 2 miesiącach normalnego noszenia to niezgodność z umową." },
      { q: "Czy mogę reklamować ubranie z H&M kupione na wyprzedaży?", a: "Tak. Cena promocyjna nie wyłącza prawa do reklamacji. Te same zasady co przy regularnej cenie." },
    ],
  },
  {
    slug: "reklamacja-zara",
    title: "Reklamacja w Zara: odzież, buty, akcesoria — jak dochodzić praw (2026)",
    description: "Ubranie z Zary ma wadę po kilku praniach? Inditex (właściciel Zary) musi odpowiedzieć na reklamację w 14 dni. 2 lata na zgłoszenie wady. Krok po kroku.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Odzież",
    faq: [
      { q: "Zara daje 30 dni na zwrot. Czy po tym terminie mogę reklamować?", a: "Tak. 30 dni na zwrot to polityka Zary. Reklamacja z tytułu wady to 2 lata od daty zakupu (art. 43c ust. 1 UPK)." },
      { q: "Ubranie z Zary się odbarwiło po praniu zgodnym z instrukcją. Co zrobić?", a: "To niezgodność z umową. Złóż reklamację w salonie Zara lub przez zara.com. Dołącz zdjęcia i dowód zakupu." },
      { q: "Zara proponuje wymianę na inny model zamiast tego samego. Czy muszę się zgodzić?", a: "Nie. Masz prawo żądać wymiany na ten sam model wolny od wad (art. 43d UPK). Jeśli model jest niedostępny — obniżenie ceny lub zwrot." },
      { q: "Ile czasu ma Zara na odpowiedź na reklamację?", a: "14 dni kalendarzowych. Brak odpowiedzi = reklamacja uznana z mocy prawa (art. 7a UPK)." },
    ],
  },
  {
    slug: "reklamacja-rossmann",
    title: "Reklamacja w Rossmann: kosmetyki, chemia, akcesoria (2026)",
    description: "Kosmetyk z Rossmann wywołał reakcję alergiczną mimo braku ostrzeżenia? Produkt chemiczny jest nieskuteczny? Masz prawo do reklamacji. Jak złożyć pismo krok po kroku.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Sklep stacjonarny",
    faq: [
      { q: "Kosmetyk z Rossmann wywołał reakcję alergiczną. Czy mogę reklamować?", a: "Tak, jeśli reakcja wynika z wadliwego składu lub braku odpowiednich ostrzeżeń na opakowaniu. Zachowaj produkt i opakowanie jako dowód." },
      { q: "Rossmann nie chce przyjąć reklamacji bez paragonu. Co zrobić?", a: "Paragon nie jest jedynym dowodem zakupu. Wystarczy wyciąg z konta lub potwierdzenie płatności kartą/BLIK." },
      { q: "Produkt z Rossmann jest przeterminowany. Co mi przysługuje?", a: "Sprzedaż przeterminowanego produktu to niezgodność z umową. Żądaj zwrotu pieniędzy i zgłoś sprawę do Inspekcji Handlowej." },
      { q: "Ile czasu mam na reklamację w Rossmann?", a: "2 lata od daty zakupu. 14 dni na odpowiedź — brak odpowiedzi = reklamacja uznana." },
    ],
  },
  {
    slug: "reklamacja-lidl",
    title: "Reklamacja w Lidl: elektronika, narzędzia, artykuły domowe (2026)",
    description: "Produkt z oferty tygodniowej Lidl się zepsuł? Lidl odpowiada za każdy sprzedany towar — niezależnie od tego czy to Silvercrest, Parkside czy Crivit. 2 lata na reklamację.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Sklep stacjonarny",
    faq: [
      { q: "Lidl mówi żebym kontaktował się z producentem Parkside/Silvercrest. Czy muszę?", a: "Nie. Art. 43b UPK: to sprzedawca (Lidl) odpowiada za niezgodność towaru z umową. Kontakt z producentem to Twoja opcja, nie obowiązek." },
      { q: "Produkt był z oferty tygodniowej i nie jest już dostępny. Czy Lidl może odmówić reklamacji?", a: "Nie. Jeśli wymiana niemożliwa, masz prawo do obniżenia ceny lub zwrotu pieniędzy (art. 43e ust. 1 UPK)." },
      { q: "Czy artykuły spożywcze z Lidl też podlegają reklamacji?", a: "Tak. Wadliwe lub przeterminowane produkty spożywcze to niezgodność z umową. Żądaj zwrotu i zgłoś sprawę do Inspekcji Handlowej." },
      { q: "Ile czasu mam na reklamację w Lidl?", a: "2 lata od daty zakupu. 14 dni na odpowiedź — brak odpowiedzi = reklamacja uznana z mocy prawa." },
    ],
  },
  {
    slug: "reklamacja-empik",
    title: "Reklamacja w Empik: książki, elektronika, gadżety — prawa konsumenta (2026)",
    description: "Produkt z Empik jest wadliwy? Empik Go nie działa? Masz 2 lata na reklamację towaru i prawo do reklamacji usługi cyfrowej. Jak złożyć pismo krok po kroku.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Elektronika",
    faq: [
      { q: "Kupiłem czytnik e-book w Empik i się zepsuł. Czy Empik jest odpowiedzialny?", a: "Tak. Art. 43b UPK: to sprzedawca (Empik) odpowiada za niezgodność towaru z umową przez 2 lata." },
      { q: "Empik Go (subskrypcja) nie działa prawidłowo. Czy mogę reklamować usługę cyfrową?", a: "Tak. Usługi cyfrowe podlegają reklamacji na podstawie art. 43k UPK. Empik ma 14 dni na odpowiedź." },
      { q: "Książka z Empik ma brakujące strony. Czy to reklamacja?", a: "Tak. Brakujące lub źle wydrukowane strony to niezgodność z umową. Żądaj wymiany na egzemplarz bez wad." },
      { q: "Ile czasu mam na reklamację w Empik?", a: "2 lata od daty zakupu dla towarów fizycznych. 14 dni na odpowiedź." },
    ],
  },
  {
    slug: "reklamacja-decathlon",
    title: "Reklamacja w Decathlon: sprzęt sportowy, odzież, rowery (2026)",
    description: "Sprzęt sportowy z Decathlon jest wadliwy? Decathlon oferuje 365 dni na zwrot, ale Twoje ustawowe prawa to 2 lata na reklamację. Jak złożyć reklamację krok po kroku.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Sport",
    faq: [
      { q: "Decathlon daje 365 dni na zwrot. Czy po tym terminie mogę reklamować?", a: "Tak. 365-dniowy zwrot to polityka Decathlon, nie ustawowe prawo. Reklamacja z tytułu wady to 2 lata (art. 43c ust. 1 UPK)." },
      { q: "Rower z Decathlon ma wadę fabryczną. Jak reklamować?", a: "Złóż reklamację w dowolnym sklepie Decathlon lub przez decathlon.pl. Decathlon powinien zorganizować odbiór roweru na swój koszt." },
      { q: "Buty sportowe z Decathlon się rozkleiły po miesiącu. Czy to wada?", a: "Tak. Buty powinny wytrzymać normalną eksploatację. Rozklejenie po miesiącu to niezgodność z umową." },
      { q: "Decathlon mówi że sprzęt był używany niezgodnie z przeznaczeniem. Czy mogą odmówić?", a: "Muszą to udowodnić ekspertyzą. Samo twierdzenie nie wystarczy — przez 2 lata obowiązuje domniemanie wady (art. 43c ust. 1 UPK)." },
    ],
  },
  {
    slug: "reklamacja-reserved",
    title: "Reklamacja w Reserved: odzież, buty, akcesoria — prawa konsumenta (2026)",
    description: "Ubranie z Reserved ma wadę po kilku praniach? LPP S.A. (właściciel Reserved) musi odpowiedzieć na reklamację w 14 dni. 2 lata na zgłoszenie wady.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Odzież",
    faq: [
      { q: "Reserved daje 30 dni na zwrot. Czy po tym mogę jeszcze reklamować?", a: "Tak. 30 dni to polityka zwrotów. Reklamacja z tytułu wady to 2 lata od daty zakupu (art. 43c ust. 1 UPK)." },
      { q: "Kurtka z Reserved rozdarła się na szwie po 3 miesiącach. Czy to wada?", a: "Tak. Rozejście się szwa po normalnym użytkowaniu to wada produkcyjna. Złóż reklamację z żądaniem wymiany lub zwrotu." },
      { q: "Czy mogę złożyć reklamację Reserved online, jeśli kupiłem w sklepie stacjonarnym?", a: "Zazwyczaj tak, ale sprawdź regulamin. Najskuteczniej: idź do dowolnego sklepu Reserved z dowodem zakupu." },
      { q: "Ile czasu ma Reserved na odpowiedź na reklamację?", a: "14 dni kalendarzowych. Brak odpowiedzi = reklamacja uznana z mocy prawa (art. 7a UPK)." },
    ],
  },
  {
    slug: "reklamacja-x-kom",
    title: "Reklamacja w x-kom: komputery, podzespoły, elektronika (2026)",
    description: "Sprzęt z x-kom jest wadliwy? Masz 2 lata na reklamację z tytułu niezgodności z umową — niezależnie od gwarancji producenta. Jak złożyć reklamację krok po kroku.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Elektronika",
    faq: [
      { q: "x-kom odsyła mnie do serwisu producenta. Czy muszę tam iść?", a: "Nie. Art. 43b UPK: to sprzedawca (x-kom) odpowiada za niezgodność towaru z umową. Gwarancja producenta to opcja dodatkowa." },
      { q: "Laptop z x-kom ma wadliwy piksel. Czy to podstawa do reklamacji?", a: "Tak, jeśli x-kom nie poinformował Cię przed zakupem o limicie wadliwych pikseli. Producenci mają normy (np. ISO 13406-2), ale Twoja umowa jest z x-kom, nie z normą." },
      { q: "x-kom przedłuża naprawę ponad miesiąc. Co mogę zrobić?", a: "Naprawa musi nastąpić w rozsądnym czasie. Jeśli się przeciąga — żądaj wymiany lub zwrotu pieniędzy (art. 43e ust. 1 UPK)." },
      { q: "Ile czasu ma x-kom na odpowiedź na reklamację?", a: "14 dni kalendarzowych. Brak odpowiedzi = reklamacja uznana z mocy prawa (art. 7a UPK)." },
    ],
  },
  {
    slug: "reklamacja-castorama",
    title: "Reklamacja w Castorama: materiały budowlane, narzędzia, ogród (2026)",
    description: "Produkt z Castoramy jest wadliwy? Masz 2 lata na reklamację. Koszty demontażu wadliwego materiału ponosi sprzedawca. Jak złożyć reklamację krok po kroku.",
    date: "2026-08-02",
    readTime: "5 min",
    category: "Dom i wnętrze",
    faq: [
      { q: "Castorama odsyła mnie do producenta. Czy muszę?", a: "Nie. Art. 43b UPK: to sprzedawca (Castorama) odpowiada za niezgodność towaru z umową." },
      { q: "Wadliwe płytki z Castoramy zostały już położone. Kto pokrywa koszt demontażu?", a: "Sprzedawca. Art. 43d ust. 4 UPK: koszty demontażu i ponownego montażu ponosi sprzedawca przy reklamacji." },
      { q: "Narzędzie elektryczne z Castoramy zepsuło się po 3 miesiącach. Czy to reklamacja?", a: "Tak. 2 lata na reklamację. Narzędzie powinno działać znacznie dłużej niż 3 miesiące przy normalnym użytkowaniu." },
      { q: "Ile czasu ma Castorama na odpowiedź na reklamację?", a: "14 dni kalendarzowych. Brak odpowiedzi = reklamacja uznana z mocy prawa (art. 7a UPK)." },
    ],
  },
  {
    slug: "reklamacja-samochodu-z-komisu",
    title: "Reklamacja samochodu z komisu: prawa kupującego i wzór pisma (2026)",
    description: "Komis twierdzi że auto sprzedane »jak stało«? Ta klauzula jest nieważna w obrocie konsumenckim (art. 43j UPK). Masz 1–2 lata na reklamację, a domniemanie wady działa przez cały ten czas. Cofnięty licznik, ukryte wady silnika, skrzynia biegów — jak złożyć skuteczne pismo.",
    date: "2026-06-23",
    readTime: "7 min",
    category: "Motoryzacja",
    titleEn: "Used Car Complaint (Dealership): Buyer's Rights and Letter Template (2026)",
    descriptionEn: "Dealer claims the car was sold 'as-is'? That clause is void in consumer (B2C) transactions (Art. 43j CRA). You have 1–2 years to complain and the presumption of defect applies throughout. Odometer fraud, hidden engine faults, gearbox problems — how to file an effective complaint.",
    categoryEn: "Automotive",
    readTimeEn: "7 min",
    faq: [
      {
        q: "Komis wpisał do umowy że »nie odpowiada za wady ukryte«. Czy to skuteczne?",
        a: "Nie. Art. 43j ustawy o prawach konsumenta zakazuje wyłączania lub ograniczania praw konsumenta z art. 43a–43i. Jakikolwiek zapis wyłączający odpowiedzialność za niezgodność towaru z umową jest bezskuteczny z mocy prawa — nie musisz go kwestionować w sądzie.",
      },
      {
        q: "Ile lat mam na reklamację samochodu kupionego w komisie?",
        a: "Standardowo 2 lata od daty zakupu (art. 43c ust. 1 UPK). Komis może skrócić ten termin do minimum 1 roku dla towarów używanych (art. 43c ust. 2 UPK) — tylko jeśli taki zapis jest wyraźnie w umowie. Jeśli umowa tego nie zawiera, obowiązuje pełne 2 lata.",
      },
      {
        q: "Odkryłem że licznik był cofnięty. Co mi przysługuje?",
        a: "Cofnięty licznik to niezgodność towaru z umową — auto nie ma cechy (przebiegu), którą miało mieć. Możesz żądać obniżenia ceny proporcjonalnej do różnicy między deklarowanym a rzeczywistym przebiegiem, albo — jeśli różnica jest istotna — odstąpić od umowy i żądać pełnego zwrotu pieniędzy.",
      },
      {
        q: "Komis naprawił auto, ale ta sama wada wróciła po 2 miesiącach. Co dalej?",
        a: "Nieskuteczna naprawa daje Ci prawo do żądania obniżenia ceny lub odstąpienia od umowy (art. 43e ust. 1 UPK). Nie musisz godzić się na kolejną próbę naprawy. Wyślij pismo żądając zwrotu pieniędzy — powołaj się na nieskuteczność poprzedniej naprawy.",
      },
      {
        q: "Kupiłem auto od osoby prywatnej, która wyłączyła rękojmię w umowie. Czy mogę reklamować?",
        a: "Co do zasady nie — w umowach C2C (konsument–konsument) rękojmia może być wyłączona i jest to skuteczne. Wyjątek: jeśli sprzedawca podstępnie zataił wadę (np. wiedział o cofniętym liczniku), wyłączenie rękojmi nie obowiązuje (art. 558 § 2 KC) — ale to trudniejsze do udowodnienia.",
      },
    ],
    faqEn: [
      {
        q: "The dealer wrote 'no liability for hidden defects' into the contract. Is this effective?",
        a: "No. Art. 43j of the Consumer Rights Act prohibits excluding consumer rights under Art. 43a–43i. Any clause excluding liability for non-conformity is void by operation of law — you do not need to challenge it in court.",
      },
      {
        q: "How many years do I have to complain about a used car bought from a dealer?",
        a: "By default 2 years from the date of purchase (Art. 43c(1) CRA). The dealer may shorten this to a minimum of 1 year for used goods (Art. 43c(2) CRA) — only if that clause is expressly stated in the contract. If the contract does not include it, the full 2 years applies.",
      },
      {
        q: "I found out the odometer was rolled back. What am I entitled to?",
        a: "Odometer fraud is non-conformity — the car lacks the characteristic (mileage) it was supposed to have. You may demand a price reduction proportional to the difference between stated and actual mileage, or — if the discrepancy is significant — withdraw from the contract and claim a full refund.",
      },
      {
        q: "The dealer repaired the car but the same defect returned 2 months later. What next?",
        a: "An ineffective repair entitles you to demand a price reduction or withdrawal from the contract (Art. 43e(1) CRA). You do not have to agree to another repair attempt. Send a letter demanding a refund — cite the ineffectiveness of the previous repair.",
      },
    ],
  },
  {
    slug: "skarga-do-uokik",
    title: "Skarga do UOKiK i Rzecznika: kiedy i jak złożyć (2026)",
    description: "Sklep ignoruje reklamacje, firma stosuje klauzule abuzywne? UOKiK nakłada kary do 10% obrotu. Rzecznik Praw Konsumentów działa bezpłatnie. Rzecznik Finansowy dla banków i ubezpieczycieli.",
    date: "2026-06-12",
    readTime: "5 min",
    category: "Ochrona konsumenta",
    titleEn: "UOKiK and Consumer Ombudsman Complaint: When and How to File (2026)",
    descriptionEn: "Store ignoring complaints or using abusive clauses? UOKiK can fine companies up to 10% of turnover. Consumer Ombudsman helps for free. Financial Ombudsman for banks and insurers.",
    categoryEn: "Consumer Protection",
    readTimeEn: "5 min",
    faq: [
      {
        q: "Czy UOKiK wyegzekwuje moją indywidualną reklamację?",
        a: "Nie. UOKiK zajmuje się praktykami naruszającymi zbiorowe interesy konsumentów — czyli działaniami firm wobec wielu klientów jednocześnie. Twoją indywidualną reklamację możesz złożyć do firmy lub zgłosić się po pomoc do Powiatowego Rzecznika Praw Konsumentów.",
      },
      {
        q: "Gdzie znaleźć Rzecznika Praw Konsumentów w moim mieście?",
        a: "Rzecznik działa przy starostwie powiatowym lub urzędzie miejskim w miastach na prawach powiatu. Listę Rzeczników znajdziesz na stronie UOKiK: uokik.gov.pl/rzecznicy_konsumentow.php. Pomoc jest bezpłatna.",
      },
      {
        q: "Kiedy zwrócić się do Rzecznika Finansowego zamiast do UOKiK?",
        a: "Do Rzecznika Finansowego (rf.gov.pl) gdy Twój spór dotyczy banku, ubezpieczyciela, funduszu inwestycyjnego lub innego podmiotu rynku finansowego. RF prowadzi bezpłatne postępowania interwencyjne i polubowne, a jego interwencje są bardzo skuteczne wobec instytucji finansowych.",
      },
      {
        q: "Czy skarga do UOKiK przerywa bieg przedawnienia mojego roszczenia?",
        a: "Nie. Skarga do UOKiK nie przerywa biegu przedawnienia — ona inicjuje postępowanie administracyjne w interesie wszystkich konsumentów. Bieg przedawnienia przerywa natomiast złożenie wniosku do Rzecznika Finansowego (art. 35 ust. 1 ustawy o Rzeczniku Finansowym) lub wszczęcie mediacji.",
      },
    ],
  },
  {
    slug: "odwolanie-od-mandatu",
    title: "Odwołanie od mandatu: policja, fotoradar, GITD — jak zakwestionować (2026)",
    description: "Mandat karny (policja): odmów przyjęcia NA MIEJSCU — po podpisaniu zasadniczo nie ma odwołania (art. 101 §1 KPW). Fotoradar CANARD i kary GITD to decyzje administracyjne — 14 dni na odwołanie z art. 127 KPA.",
    date: "2026-06-12",
    readTime: "5 min",
    category: "Mandat",
    titleEn: "Traffic Fine Appeal: Police, Speed Camera, GITD — How to Challenge (2026)",
    descriptionEn: "Criminal fine (police): refuse ON THE SPOT — once signed it is final (Art. 101 §1 CCP). Speed camera CANARD and GITD penalties are administrative decisions — 14 days to appeal under Art. 127 CAP.",
    categoryEn: "Traffic Fine",
    readTimeEn: "5 min",
    faq: [
      {
        q: "Czy mogę odwołać się od mandatu karnego który już przyjąłem?",
        a: "Zasadniczo nie. Art. 101 §1 KPW: mandat staje się prawomocny z chwilą podpisania. Wyjątek: art. 101 §2 KPW pozwala na uchylenie przez sąd gdy czyn nie był wykroczeniem, ukarano niewłaściwą osobę lub kara była za wysoka. To wąski wyjątek — samo twierdzenie że nie naruszyłeś przepisów nie wystarczy.",
      },
      {
        q: "Co grozi za odmowę przyjęcia mandatu karnego?",
        a: "Nic. Art. 97 §2 KPW wprost stanowi że funkcjonariusz nie może nałożyć mandatu jeżeli obwiniony odmawia jego przyjęcia. Sprawa trafia do sądu — sąd ocenia czy wykroczenie miało miejsce. Nie możesz być ukarany za samą odmowę.",
      },
      {
        q: "Mandat z fotoradaru CANARD — jak się odwołać?",
        a: "To administracyjna kara pieniężna, nie mandat karny. Masz 14 dni od doręczenia decyzji na odwołanie do GITD (Główny Inspektorat Transportu Drogowego) — art. 127 §1 KPA. Jeśli decyzja GITD jest niekorzystna, kolejna droga to skarga do Wojewódzkiego Sądu Administracyjnego w ciągu 30 dni.",
      },
      {
        q: "Prywatna firma parkingowa wystawiła mi mandat. Czy muszę płacić?",
        a: "To nie jest mandat prawny — to roszczenie cywilnoprawne z umowy. Możesz je zakwestionować pisemnie. Firma musi wytoczyć Ci sprawę cywilną żeby wyegzekwować należność. Rażąco wygórowane opłaty dodatkowe bywają uznawane za klauzule abuzywne (art. 385¹ KC).",
      },
    ],
  },
  {
    slug: "zakup-na-raty-zwrot",
    title: "Zakup na raty przez PayU: co z kredytem gdy zwracasz towar (2026)",
    description: "Kupiłeś na raty przez PayU i chcesz zwrócić towar? Art. 31 ustawy o kredycie konsumenckim: odstąpienie od umowy sprzedaży automatycznie wygasza umowę kredytową. Nie możesz zostać z ratami bez towaru. Krok po kroku.",
    date: "2026-06-11",
    readTime: "5 min",
    category: "Sklep internetowy",
    titleEn: "Bought on Instalments via PayU: What Happens to the Loan When You Return the Goods (2026)",
    descriptionEn: "Bought on instalments via PayU and want to return? Art. 31 of the Consumer Credit Act: withdrawing from the sales contract automatically cancels the credit agreement. You cannot be left with instalments and no product.",
    categoryEn: "Online Store",
    readTimeEn: "5 min",
    faq: [
      {
        q: "Czy mogę zostać z ratami jeśli sklep nie dostarczy towaru?",
        a: "Nie. Zakup na raty przez PayU to kredyt wiązany (art. 29 ustawy o kredycie konsumenckim). Jeśli odstąpisz od umowy sprzedaży lub sprzedawca jej nie wykona, umowa kredytowa wygasa z mocy art. 31 UKK. Sprzedawca zwraca środki do PayU, Twój dług odpada.",
      },
      {
        q: "Ile dni mam na zwrot towaru kupionego na raty online?",
        a: "14 dni od otrzymania towaru na podstawie art. 27 ustawy o prawach konsumenta — niezależnie od tego, że kupiłeś na raty. Jeśli sprzedawca zmienił termin dostawy bez Twojej zgody, możesz odstąpić niezależnie od 14-dniowego terminu.",
      },
      {
        q: "Złożyłem odstąpienie. Kiedy PayU anuluje raty?",
        a: "Sprzedawca ma 14 dni na zwrot środków do PayU od momentu otrzymania Twojego oświadczenia o odstąpieniu (art. 32 UPK). Poinformuj PayU o złożonym odstąpieniu jednocześnie ze sprzedawcą i poproś o wstrzymanie płatności do czasu rozliczenia.",
      },
      {
        q: "Sprzedawca nie zwraca pieniędzy do PayU i dalej spłacam raty. Co zrobić?",
        a: "Złóż skargę do PayU jako kredytodawcy — ma narzędzia do dochodzenia zwrotu od sprzedawcy. Jednocześnie złóż skargę do UOKiK. Masz też prawo wezwać sprzedawcę do zapłaty odsetek ustawowych za każdy dzień opóźnienia po upływie 14-dniowego terminu.",
      },
      {
        q: "Czy PayU Raty to zawsze kredyt wiązany?",
        a: "Tak, jeśli kredyt został udzielony bezpośrednio na zakup konkretnego towaru u konkretnego sprzedawcy w momencie transakcji — to kredyt wiązany z art. 29 UKK. Inaczej niż karta kredytowa czy limit w koncie, które są kredytami ogólnymi.",
      },
    ],
  },
  {
    slug: "reklamacja-zalando",
    title: "Reklamacja Zalando: prawa konsumenta i jak złożyć pismo (2026)",
    description: "Zalando odmówiło reklamacji albo nie odpowiada? Art. 43b ustawy o prawach konsumenta: 2 lata na reklamację, koszty odesłania pokrywa Zalando. Brak odpowiedzi w 14 dniach = reklamacja uznana. Wzór pisma.",
    date: "2026-06-09",
    readTime: "5 min",
    category: "Sklep internetowy",
    titleEn: "Zalando Complaint: Consumer Rights and How to File (2026)",
    descriptionEn: "Zalando refused your complaint or isn't responding? Art. 43b Consumer Rights Act: 2 years to complain, return shipping covered by Zalando. No reply in 14 days = complaint accepted by law.",
    categoryEn: "Online Store",
    readTimeEn: "5 min",
    faq: [
      {
        q: "Czy mogę złożyć reklamację po upływie 100-dniowego okresu zwrotów Zalando?",
        a: "Tak. Polityka 100-dniowych zwrotów to oferta handlowa Zalando, a nie Twoje ustawowe prawo. Reklamacja z tytułu niezgodności towaru z umową (art. 43b UPK) obowiązuje przez 2 lata od odbioru towaru, niezależnie od polityki zwrotów.",
      },
      {
        q: "Ile dni ma Zalando na odpowiedź na reklamację?",
        a: "14 dni kalendarzowych (art. 7a ustawy o prawach konsumenta). Brak odpowiedzi w tym terminie = reklamacja uznana za zasadną z mocy prawa.",
      },
      {
        q: "Czy muszę płacić za odesłanie reklamowanego towaru do Zalando?",
        a: "Nie. Koszty odesłania towaru w ramach reklamacji (naprawa lub wymiana) ponosi Zalando jako sprzedawca — art. 43d ust. 4 ustawy o prawach konsumenta. Dotyczy to kosztu opłat pocztowych i transportu.",
      },
      {
        q: "Zalando mówi że wada powstała z mojej winy. Co zrobić?",
        a: "Zażądaj pisemnego uzasadnienia z wynikami ekspertyzy technicznej. Samo stwierdzenie emailem nie wystarczy. Art. 43c ust. 1 UPK: przez 2 lata od dostarczenia towaru domniemywa się, że wada istniała już przy dostawie — to Zalando musi obalić to domniemanie ekspertyzą, nie Ty musisz dowodzić wady.",
      },
      {
        q: "Kupiłem od sprzedawcy Zalando Partner, nie od Zalando. Do kogo piszę?",
        a: "Do sprzedawcy partnerskiego — to on zawarł z Tobą umowę i odpowiada za niezgodność towaru z umową. Dane sprzedawcy znajdziesz w potwierdzeniu zamówienia. Zalando jako platforma nie odpowiada za towar partnerów, ale często pośredniczy w procesie reklamacji.",
      },
    ],
  },
  {
    slug: "reklamacja-do-ubezpieczyciela",
    title: "Reklamacja do ubezpieczyciela: OC, AC, NNW — prawa i wzór pisma (2026)",
    description: "Ubezpieczyciel odmówił wypłaty lub zaniżył odszkodowanie? Art. 817 KC: 30 dni na wypłatę. Brak odpowiedzi na reklamację w 30 dniach = uznana za zasadną. Jak napisać skuteczne pismo do towarzystwa ubezpieczeniowego.",
    date: "2026-06-05",
    readTime: "6 min",
    category: "Ubezpieczenia",
    titleEn: "Insurance Complaint: OC, AC, NNW — Your Rights and Letter Template (2026)",
    descriptionEn: "Insurer refused payout or underpaid? Art. 817 CC: 30 days to pay. No reply to complaint in 30 days = accepted by law. How to write an effective letter to a Polish insurance company.",
    categoryEn: "Insurance",
    readTimeEn: "6 min",
    faq: [
      {
        q: "Ile czasu ma ubezpieczyciel na wypłatę odszkodowania?",
        a: "Zgodnie z art. 817 § 1 Kodeksu cywilnego — 30 dni od daty zawiadomienia o szkodzie. Jeśli wyjaśnienie okoliczności jest niemożliwe w tym terminie, maksymalnie 14 dni od ich wyjaśnienia, ale nie więcej niż 90 dni od zgłoszenia. Za każdy dzień opóźnienia należą Ci się odsetki ustawowe za opóźnienie.",
      },
      {
        q: "Ile dni ma ubezpieczyciel na odpowiedź na reklamację?",
        a: "30 dni kalendarzowych (art. 6 ustawy o rozpatrywaniu reklamacji przez podmioty rynku finansowego). Wyjątkowo 60 dni przy szczególnie skomplikowanych sprawach. Brak odpowiedzi w terminie = reklamacja uznana za zasadną (art. 8 tej ustawy).",
      },
      {
        q: "Ubezpieczyciel zaniżył wartość szkody w AC. Czy mogę się odwołać?",
        a: "Tak. Masz prawo zakwestionować wycenę i powołać własnego rzeczoznawcę. Ubezpieczyciel musi wykazać metodologię wyceny. Klauzule OWU ograniczające odszkodowanie do kosztorysu z amortyzacją i najtańszymi zamiennikami są często kwestionowane przez sądy jako niezgodne z celem ubezpieczenia AC.",
      },
      {
        q: "Kiedy ubezpieczyciel może zgodnie z prawem odmówić wypłaty?",
        a: "Tylko gdy zdarzenie mieści się w wyłączeniach OWU, które były Ci dostarczone przed zawarciem umowy. Niejednoznaczne postanowienia OWU tłumaczy się na korzyść ubezpieczonego (art. 12 ust. 3 ustawy o działalności ubezpieczeniowej). Wyłączenia sprzeczne z przepisami bezwzględnie obowiązującymi są nieważne (art. 807 KC).",
      },
      {
        q: "Co zrobić jeśli reklamacja do ubezpieczyciela nie pomoże?",
        a: "Złóż wniosek do Rzecznika Finansowego (rf.gov.pl) — bezpłatne postępowanie interwencyjne lub polubowne. Możesz też złożyć skargę do KNF lub skierować sprawę do sądu. Złożenie wniosku do RF zawiesza bieg przedawnienia roszczenia.",
      },
    ],
  },
  {
    slug: "reklamacja-dewelopera",
    title: "Reklamacja dewelopera: wady mieszkania i jak je egzekwować (2026)",
    description: "Deweloper nie usunął wad z protokołu odbioru? Art. 43 nowej ustawy deweloperskiej: 30 dni na usunięcie wad. Rękojmia KC — 5 lat na reklamację wad nieruchomości. Jak napisać skuteczne pismo.",
    date: "2026-06-01",
    readTime: "6 min",
    category: "Nieruchomości",
    titleEn: "Developer Complaint: Flat Defects and How to Enforce Your Rights (2026)",
    descriptionEn: "Developer didn't fix defects from the handover protocol? Art. 43 Developer Act: 30 days to fix. Civil Code warranty — 5 years for property defects. How to write an effective letter.",
    categoryEn: "Property",
    readTimeEn: "6 min",
    faq: [
      {
        q: "Ile lat mam na reklamację wad mieszkania od dewelopera?",
        a: "5 lat od daty odbioru lokalu — to termin rękojmi za wady nieruchomości z art. 568 § 1 Kodeksu cywilnego. Niezależnie od gwarancji dewelopera, która może być krótsza.",
      },
      {
        q: "Deweloper nie usunął wad wskazanych w protokole odbioru. Co zrobić?",
        a: "Art. 43 ust. 1 nowej ustawy deweloperskiej: deweloper ma 30 dni na usunięcie wad z protokołu. Po tym terminie możesz wyznaczyć dodatkowy termin, a po jego upływie — usunąć wady na koszt dewelopera lub żądać obniżenia ceny.",
      },
      {
        q: "Czy mogę odmówić odbioru mieszkania z powodu wad?",
        a: "Tak — jeśli wada jest istotna. Art. 41 ust. 4 ustawy deweloperskiej z 2021 r. (obowiązuje dla umów od 1.07.2022 r.): nabywca może odmówić odbioru i wyznaczyć termin usunięcia istotnej wady. Przy wadach nieistotnych odbioru dokonujesz z zastrzeżeniami wpisanymi do protokołu.",
      },
      {
        q: "Deweloper twierdzi że wady wynikają z mojego użytkowania. Co robić?",
        a: "Art. 556³ KC: jeśli wada ujawniła się w ciągu roku od odbioru, domniemywa się że istniała w chwili wydania lokalu. To deweloper musi obalić to domniemanie ekspertyzą — nie Ty musisz dowodzić że wada jest fabryczna.",
      },
    ],
  },
  {
    slug: "odwolanie-od-decyzji-zus",
    title: "Odwołanie od decyzji ZUS: jak i gdzie złożyć — krok po kroku (2026)",
    description: "ZUS odmówił zasiłku, renty lub emerytury? Masz 1 miesiąc na odwołanie do sądu pracy — nie do ZUS. Art. 477⁹ KPC i art. 83 uSUS. Postępowanie wolne od opłat. Jak napisać skuteczne odwołanie.",
    date: "2026-05-27",
    readTime: "6 min",
    category: "ZUS / US",
    titleEn: "ZUS Appeal: How and Where to File — Step by Step (2026)",
    descriptionEn: "ZUS refused your benefit, pension or disability payment? You have 1 month to appeal to the labour court — not to ZUS. Art. 477⁹ CPC. Proceedings are free of court fees.",
    categoryEn: "ZUS / Social Insurance",
    readTimeEn: "6 min",
    faq: [
      {
        q: "Ile czasu mam na odwołanie od decyzji ZUS?",
        a: "1 miesiąc od daty doręczenia decyzji (art. 477¹⁰ § 1 KPC). Termin jest procesowy — liczony od faktycznego odbioru pisma. Po upływie miesiąca odwołanie jest spóźnione i sąd je odrzuci.",
      },
      {
        q: "Gdzie składa się odwołanie od decyzji ZUS?",
        a: "Pismo adresujesz do właściwego sądu rejonowego — wydziału pracy i ubezpieczeń społecznych (sprawy o świadczenia: zasiłki, renty, emerytury) lub sądu okręgowego (sprawy o składki i obowiązek ubezpieczenia — art. 477⁸ KPC). Pismo składasz fizycznie w ZUS lub wysyłasz pocztą na adres ZUS. ZUS przekazuje je do sądu lub sam zmienia decyzję w 30 dni (art. 83a uSUS).",
      },
      {
        q: "Czy odwołanie od decyzji ZUS jest płatne?",
        a: "Nie. Postępowanie w sprawach z zakresu ubezpieczeń społecznych jest wolne od opłat sądowych dla ubezpieczonego (art. 96 ust. 1 pkt 4 ustawy o kosztach sądowych w sprawach cywilnych).",
      },
      {
        q: "Czy ZUS może sam zmienić swoją decyzję po otrzymaniu odwołania?",
        a: "Tak. Art. 83a ust. 2 uSUS: ZUS może w ciągu 30 dni od otrzymania odwołania samodzielnie zmienić lub uchylić zaskarżoną decyzję. Jeśli tego nie zrobi, przekazuje odwołanie do sądu wraz z aktami sprawy.",
      },
    ],
  },
  {
    slug: "wezwanie-do-zaplaty",
    title: "Wezwanie do zapłaty: wzór pisma z przepisami KC (2026)",
    description: "Ktoś Ci nie zapłacił? Formalne wezwanie z art. 455 KC uruchamia bieg odsetek. Przy transakcjach B2B: odsetki 10% + zryczałtowane koszty 40/70/100 EUR z ustawy o transakcjach handlowych. Wzór pisma PDF.",
    date: "2026-05-23",
    readTime: "5 min",
    category: "Windykacja",
    titleEn: "Payment Demand Letter: Template with Polish Civil Code (2026)",
    descriptionEn: "Someone owes you money? A formal demand under Art. 455 CC starts interest running. B2B: 10% interest + flat-rate recovery costs €40/70/100 under the Commercial Transactions Act.",
    categoryEn: "Debt Recovery",
    readTimeEn: "5 min",
    faq: [
      {
        q: "Co daje formalne wezwanie do zapłaty w porównaniu do zwykłego przypomnienia?",
        a: "Wezwanie z art. 455 KC ustala datę wymagalności długu i uruchamia bieg odsetek ustawowych za opóźnienie od dnia następnego po terminie w wezwaniu. Jest też dowodem w postępowaniu sądowym — warunkiem uzyskania nakazu zapłaty.",
      },
      {
        q: "Ile wynoszą odsetki za opóźnienie w zapłacie?",
        a: "Odsetki ustawowe za opóźnienie (art. 481 § 2 KC) = stopa referencyjna NBP + 5,5 punktu procentowego. Dla transakcji handlowych między przedsiębiorcami: stopa NBP + 10 pp (ustawa o transakcjach handlowych).",
      },
      {
        q: "Ile mam czasu na dochodzenie długu zanim się przedawni?",
        a: "Ogólny termin przedawnienia: 6 lat (art. 118 KC). Dla roszczeń z działalności gospodarczej i faktur między przedsiębiorcami: 3 lata. Termin liczy się od daty wymagalności długu.",
      },
      {
        q: "Dłużnik nie zapłacił po wezwaniu — co dalej?",
        a: "Postępowanie upominawcze (art. 498 KPC): sąd wydaje nakaz zapłaty bez rozprawy na podstawie wezwania i dokumentów. Opłata 5% wartości roszczenia. Przy braku sprzeciwu dłużnika nakaz jest prawomocny i możesz skierować sprawę do komornika.",
      },
    ],
  },
  {
    slug: "reklamacja-uslugi",
    title: "Reklamacja usługi: remont, naprawa, instalacja — prawa i wzór pisma (2026)",
    description: "Firma remontowa zostawiła wady? Hydraulik nie naprawił usterki? Art. 636 KC: możesz wyznaczyć termin na poprawki i zlecić je innej firmie na koszt wykonawcy. Rękojmia 5 lat przy nieruchomościach. Wzór pisma.",
    date: "2026-05-19",
    readTime: "5 min",
    category: "Usługi",
    titleEn: "Service Complaint: Renovation, Repair, Installation — Rights and Letter Template (2026)",
    descriptionEn: "Renovation company left defects? Plumber didn't fix the fault? Art. 636 CC: set a deadline and commission another contractor at the first one's cost. 5-year warranty for property work.",
    categoryEn: "Services",
    readTimeEn: "5 min",
    faq: [
      {
        q: "Ile lat mam na reklamację wadliwego remontu?",
        a: "5 lat od oddania dzieła — przy usługach dotyczących nieruchomości (remont, instalacje, prace budowlane). 2 lata — przy usługach dotyczących rzeczy ruchomych (naprawa sprzętu). Podstawa: art. 568 § 1 KC w zw. z art. 638 KC.",
      },
      {
        q: "Firma remontowa robi remont niezgodnie z umową. Czy muszę czekać na koniec?",
        a: "Nie. Art. 636 § 1 KC: możesz wezwać wykonawcę do zmiany sposobu wykonania i wyznaczyć termin. Jeśli nie zmieni sposobu — możesz odstąpić od umowy lub zlecić wykonanie innej firmie na koszt i ryzyko pierwszego wykonawcy.",
      },
      {
        q: "Wykonawca twierdzi że wada wynika z mojego użytkowania. Co zrobić?",
        a: "Art. 556³ KC (stosowany przez analogię): jeśli wada ujawniła się w ciągu roku od wydania dzieła, domniemywa się że istniała przy wydaniu. Wykonawca musi obalić to domniemanie ekspertyzą — nie Ty musisz dowodzić że wada jest jego winą.",
      },
      {
        q: "Czy mogę żądać zwrotu pieniędzy za wadliwą usługę?",
        a: "Tak, jeśli wada jest istotna i wykonawca jej nie usunął. Art. 638 KC w zw. z art. 560 § 1 KC: przy istotnej wadzie możesz odstąpić od umowy i żądać zwrotu wynagrodzenia. Przy wadzie nieistotnej: obniżenie wynagrodzenia.",
      },
    ],
  },
  {
    slug: "odszkodowanie-za-opozniony-lot",
    title: "Odszkodowanie za opóźniony i odwołany lot: 250–600 EUR z rozporządzenia UE (2026)",
    description: "Lot opóźniony ponad 3 godziny lub odwołany? Rozporządzenie (WE) 261/2004: 250–600 EUR odszkodowania. Awaria techniczna NIE jest wyjątkiem (wyrok TSUE C-549/07). Jak napisać roszczenie do linii lotniczej.",
    date: "2026-05-15",
    readTime: "6 min",
    category: "Podróże",
    titleEn: "Flight Delay and Cancellation Compensation: €250–600 under EU Regulation (2026)",
    descriptionEn: "Flight delayed over 3 hours or cancelled? EU Regulation 261/2004: €250–600 compensation. Technical failure is NOT an exception (CJEU C-549/07). How to write a claim to the airline.",
    categoryEn: "Travel",
    readTimeEn: "6 min",
    faq: [
      {
        q: "Od jakiego opóźnienia przysługuje odszkodowanie za lot?",
        a: "Od 3 godzin opóźnienia przy przylocie do celu (nie przy odlocie). Wyrok TSUE C-402/07 Sturgeon: pasażerowie opóźnionych lotów mają te same prawa co pasażerowie odwołanych. Odszkodowanie: 250, 400 lub 600 EUR zależnie od długości trasy (art. 7 rozporządzenia 261/2004).",
      },
      {
        q: "Linia twierdzi że opóźnienie wynikało z awarii technicznej. Czy mam prawo do odszkodowania?",
        a: "Tak, w większości przypadków. Wyrok TSUE C-549/07 (Wallentin-Hermann v. Alitalia): awaria techniczna NIE jest nadzwyczajną okolicznością zwalniającą z odszkodowania, chyba że wynika z ukrytej wady fabrycznej wykrytej przez producenta. Regularne usterki to ryzyko wchodzące w zakres działalności linii.",
      },
      {
        q: "Czy odszkodowanie przysługuje przy lotach spoza UE?",
        a: "Rozporządzenie 261/2004 obejmuje: wszystkie loty wylatujące z lotnisk w UE (niezależnie od linii) oraz loty przylatujące do UE obsługiwane przez przewoźnika z siedzibą w UE. Lot z Polski do Turcji — tak. Lot z Turcji do Polski obsługiwany przez Turkish Airlines — nie.",
      },
      {
        q: "Ile mam czasu na złożenie roszczenia do linii?",
        a: "Rozporządzenie nie określa terminu. W Polsce stosuje się ogólny termin przedawnienia — 3 lata od daty lotu (art. 118 KC). Składaj jak najszybciej — linie mają pełną dokumentację lotu, Ty możesz ją tracić z czasem.",
      },
    ],
  },
  {
    slug: "reklamacja-odrzucona",
    title: "Reklamacja odrzucona — co zrobić dalej? [Poradnik 2026]",
    description: "Sklep nie uznał reklamacji? Masz prawo do odwołania. Dowiedz się jak obalić odmowę z powołaniem na art. 43c ust. 1 UPK — domniemanie wady, ekspertyza na koszt sklepu, zwrot po nieskutecznej wymianie.",
    date: "2026-05-11",
    readTime: "6 min",
    category: "Reklamacja",
    faq: [
      {
        q: "Ile mam czasu na odwołanie od odmowy reklamacji?",
        a: "Przepisy nie przewidują osobnego terminu na odwołanie — liczy się 2-letni termin odpowiedzialności sprzedawcy od daty dostarczenia towaru (art. 43c ust. 1 UPK). Im szybciej wyślesz odwołanie, tym lepiej — dowody są świeższe i łatwiej udowodnić chronologię zdarzeń.",
      },
      {
        q: "Sklep twierdzi że wada wynika z mojego użytkowania. Co robić?",
        a: "Sklep musi to udowodnić ekspertyzą techniczną na własny koszt — samo stwierdzenie w mailu nie wystarczy. Przez pierwsze 2 lata od dostarczenia towaru obowiązuje domniemanie (art. 43c ust. 1 UPK), że niezgodność istniała już w chwili dostarczenia. To sprzedawca musi obalić to domniemanie, nie Ty musisz dowodzić że towar był wadliwy.",
      },
      {
        q: "Wymienili towar reklamacyjnie, ale po kilku miesiącach ta sama wada wróciła. Co mi przysługuje?",
        a: "Zgodnie z art. 43e ust. 1 ustawy o prawach konsumenta, gdy naprawa lub wymiana okazała się nieskuteczna, masz prawo żądać obniżenia ceny lub odstąpienia od umowy (zwrotu pieniędzy). Nie musisz zgadzać się na kolejną wymianę.",
      },
      {
        q: "Czy mogę złożyć skargę do UOKiK na sklep który odrzuca reklamacje?",
        a: "Tak. Jeśli sklep systematycznie odrzuca reklamacje bez podstawy prawnej, możesz złożyć zawiadomienie do UOKiK o podejrzeniu stosowania praktyk naruszających zbiorowe interesy konsumentów. UOKiK może wszcząć postępowanie i nałożyć karę finansową na przedsiębiorcę.",
      },
      {
        q: "Czy odwołanie od odmowy reklamacji muszę wysłać listem poleconym?",
        a: "Nie jest to wymagane przepisami, ale zalecane. List polecony za potwierdzeniem odbioru daje Ci dowód że pismo dotarło i kiedy — co jest ważne jeśli sprawa trafi do sądu. Email z potwierdzeniem odczytu to minimum, list polecony to większe bezpieczeństwo.",
      },
    ],
  },
  {
    slug: "reklamacja-sklep-internetowy",
    title: "Jak napisać skuteczną reklamację do sklepu internetowego (wzór 2026)",
    description: "Krok po kroku: jak napisać reklamację do sklepu internetowego z powołaniem na art. 43b ustawy o prawach konsumenta. Sklep ma 14 dni na odpowiedź, brak odpowiedzi to uznanie reklamacji.",
    date: "2026-05-07",
    readTime: "5 min",
    category: "Sklep internetowy",
    titleEn: "How to File an Effective Complaint to an Online Store (Template 2026)",
    descriptionEn: "Step-by-step: how to write a complaint to an online store citing Art. 43b of the Consumer Rights Act. The store has 14 days to respond; silence means the complaint is accepted.",
    categoryEn: "Online Store",
    readTimeEn: "5 min",
    faq: [
      {
        q: "Czy mogę reklamować towar po roku od zakupu?",
        a: "Tak. Termin na reklamację to 2 lata od daty otrzymania towaru, nie rok. Przez cały ten czas obowiązuje domniemanie, że wada istniała przy zakupie (art. 43c ust. 1 ustawy o prawach konsumenta).",
      },
      {
        q: "Sklep mówi że przyjmuje tylko gwarancję producenta. Czy to prawda?",
        a: "Nie. Gwarancja producenta i prawa z ustawy o prawach konsumenta to dwa osobne mechanizmy. Sklep jako sprzedawca odpowiada za niezgodność towaru z umową przez 2 lata na podstawie art. 43b, niezależnie od gwarancji producenta.",
      },
      {
        q: "Ile dni ma sklep na odpowiedź na reklamację?",
        a: "14 dni kalendarzowych. Jeśli sklep nie odpowie w tym terminie, reklamacja jest uznana za zasadną z mocy prawa (art. 7a ustawy o prawach konsumenta).",
      },
      {
        q: "Sklep zaproponował bon zamiast zwrotu pieniędzy. Czy muszę go przyjąć?",
        a: "Nie. Bon to propozycja sklepu, nie Twój obowiązek. Jeśli żądasz zwrotu pieniędzy na podstawie art. 43e ust. 1, sklep musi przelać środki na konto. Bon możesz przyjąć, ale nie musisz.",
      },
      {
        q: "Czego mogę żądać w reklamacji: naprawy, wymiany czy zwrotu?",
        a: "W pierwszej kolejności możesz wybrać między naprawą a wymianą (art. 43d ust. 1). Jeśli naprawa lub wymiana okazała się nieskuteczna albo sklep odmówił obu, możesz żądać obniżenia ceny lub pełnego zwrotu pieniędzy (art. 43e ust. 1 ustawy o prawach konsumenta).",
      },
    ],
    faqEn: [
      {
        q: "Can I complain about a product more than a year after purchase?",
        a: "Yes. The complaint period is 2 years from the date you received the goods, not one year. Throughout this period it is presumed that the defect existed at the time of purchase (Art. 43c §1 of the Consumer Rights Act).",
      },
      {
        q: "The store says it only accepts manufacturer warranty claims. Is that true?",
        a: "No. The manufacturer's warranty and rights under the Consumer Rights Act are two separate mechanisms. The store as seller is liable for non-conformity for 2 years under Art. 43b, regardless of the manufacturer's warranty.",
      },
      {
        q: "How many days does the store have to respond to a complaint?",
        a: "14 calendar days. If the store does not respond within this period, the complaint is deemed accepted by force of law (Art. 7a of the Consumer Rights Act).",
      },
      {
        q: "The store offered a voucher instead of a refund. Do I have to accept it?",
        a: "No. A voucher is the store's proposal, not your obligation. If you demand a refund under Art. 43e §1, the store must transfer the funds to your account. You may accept the voucher if you wish, but you do not have to.",
      },
      {
        q: "What can I demand in a complaint: repair, replacement or refund?",
        a: "You may first choose between repair and replacement (Art. 43d §1). If repair or replacement proved ineffective or the store refused both, you may demand a price reduction or full refund (Art. 43e §1 of the Consumer Rights Act).",
      },
    ],
  },
  {
    slug: "reklamacja-allegro",
    title: "Reklamacja na Allegro: co zrobić gdy sprzedawca odmawia (2026)",
    description: "Sprzedawca na Allegro odrzucił Twoją reklamację? Dowiedz się jakie masz prawa jako konsument i jak napisać pismo które zmusi go do odpowiedzi w 14 dniach.",
    date: "2026-05-03",
    readTime: "6 min",
    category: "Allegro",
    titleEn: "Complaint on Allegro: What to Do When the Seller Refuses (2026)",
    descriptionEn: "Did an Allegro seller reject your complaint? Find out your rights as a consumer and how to write a letter that forces a response within 14 days.",
    categoryEn: "Allegro",
    readTimeEn: "6 min",
    faq: [
      {
        q: "Czy mogę reklamować towar kupiony od osoby prywatnej na Allegro?",
        a: "Ustawa o prawach konsumenta dotyczy tylko zakupów od przedsiębiorców. Przy zakupie od osoby prywatnej (bez NIP na profilu) możesz powołać się na rękojmię z Kodeksu cywilnego — termin to 2 lata od wydania towaru (art. 568 §1 KC), ale egzekwowanie jest trudniejsze, bo sprzedawca prywatny może wyłączyć lub ograniczyć rękojmię.",
      },
      {
        q: "Ile czasu ma sprzedawca na Allegro na odpowiedź na reklamację?",
        a: "14 dni kalendarzowych. Brak odpowiedzi w tym terminie to uznanie reklamacji za zasadną z mocy art. 7a ustawy o prawach konsumenta.",
      },
      {
        q: "Czy muszę odesłać towar zanim sprzedawca uzna reklamację?",
        a: "Nie. Nie odsyłaj towaru przed otrzymaniem decyzji o uznaniu reklamacji. Koszty ewentualnego odesłania w celu naprawy lub wymiany ponosi sprzedawca.",
      },
      {
        q: "Sprzedawca twierdzi że towar był sprawny przy wysyłce. Co zrobić?",
        a: "To niewystarczający argument. Zgodnie z art. 43c ust. 1 ustawy o prawach konsumenta, przez 2 lata od dostarczenia towaru obowiązuje domniemanie że wada istniała w chwili dostarczenia. Sprzedawca musi obalić to domniemanie ekspertyzą, nie słownym twierdzeniem.",
      },
      {
        q: "Sprzedawca zaproponował voucher zamiast zwrotu. Czy muszę go przyjąć?",
        a: "Nie. Jeśli żądasz zwrotu pieniędzy, sprzedawca musi przelać środki. Voucher jest propozycją handlową, nie obowiązkiem konsumenta.",
      },
    ],
    faqEn: [
      {
        q: "Can I file a complaint about goods bought from a private individual on Allegro?",
        a: "The Consumer Rights Act applies only to purchases from businesses. When buying from a private individual (no NIP on the profile) you can rely on the Civil Code warranty — the period is 2 years from delivery (Art. 568 §1 CC), but enforcement is harder because a private seller can exclude or limit the warranty.",
      },
      {
        q: "How many days does an Allegro seller have to respond to a complaint?",
        a: "14 calendar days. No response within that period means the complaint is accepted by force of law under Art. 7a of the Consumer Rights Act.",
      },
      {
        q: "Do I have to return the goods before the seller accepts my complaint?",
        a: "No. Do not return the goods before receiving the seller's decision on the complaint. The cost of any return for repair or replacement is borne by the seller.",
      },
      {
        q: "The seller claims the item was working when shipped. What should I do?",
        a: "That is insufficient. Under Art. 43c §1 of the Consumer Rights Act, for 2 years from delivery it is presumed that the defect existed at the time of delivery. The seller must rebut this presumption with an expert assessment — a verbal claim is not enough.",
      },
      {
        q: "The seller offered a voucher instead of a refund. Do I have to accept it?",
        a: "No. If you demand a refund, the seller must transfer the funds. A voucher is a commercial offer, not a consumer obligation.",
      },
    ],
  },
  {
    slug: "bank-odmawia-zwrotu",
    title: "Bank odmawia zwrotu pieniędzy: Twoje prawa i jak je egzekwować",
    description: "Nieautoryzowana transakcja, błędny przelew lub naliczona opłata? Bank ma obowiązek zwrotu do końca następnego dnia roboczego (art. 46 ustawy o usługach płatniczych). Jak napisać skuteczne pismo.",
    date: "2026-04-29",
    readTime: "5 min",
    category: "Bank",
    titleEn: "Bank Refuses Refund: Your Rights and How to Enforce Them",
    descriptionEn: "Unauthorised transaction, incorrect charge or refused refund? The bank must return the money by end of next business day (Art. 46 of the Payment Services Act). How to write an effective letter.",
    categoryEn: "Bank",
    readTimeEn: "5 min",
    faq: [
      {
        q: "Ile czasu ma bank na zwrot pieniędzy po zgłoszeniu nieautoryzowanej transakcji?",
        a: "Bank musi zwrócić pieniądze niezwłocznie, nie później niż do końca następnego dnia roboczego po dniu zgłoszenia (art. 46 ust. 1 ustawy o usługach płatniczych). Bank może potem prowadzić dochodzenie, ale środki muszą wrócić najpierw.",
      },
      {
        q: "Bank twierdzi że logowanie było prawidłowe i nie zwróci pieniędzy. Czy to zgodne z prawem?",
        a: "Nie. Art. 45 ust. 2 ustawy o usługach płatniczych stanowi wprost, że samo wykazanie zarejestrowanego użycia instrumentu płatniczego nie wystarcza do udowodnienia że transakcja była autoryzowana. Ciężar dowodu spoczywa na banku.",
      },
      {
        q: "Czy bank może odmówić zwrotu jeśli sam wpisałem kod BLIK lub dane karty?",
        a: "Jeśli padłeś ofiarą oszustwa i działałeś pod wpływem manipulacji (np. podszywanie się pod znajomego), bank musi udowodnić rażące niedbalstwo z Twojej strony. Samo wpisanie kodu pod wpływem oszustwa to co do zasady nie jest rażące niedbalstwo.",
      },
      {
        q: "Kiedy bank może zgodnie z prawem odmówić zwrotu?",
        a: "Bank może odmówić gdy udowodni że działałeś umyślnie (sam zleciłeś transakcję) lub dopuściłeś się rażącego niedbalstwa, na przykład zapisałeś PIN razem z kartą lub przekazałeś dane logowania osobie trzeciej świadomie.",
      },
      {
        q: "Co zrobić jeśli bank nadal odmawia po złożeniu pisemnej reklamacji?",
        a: "Złóż skargę do Rzecznika Finansowego (rf.gov.pl). Banki bardzo poważnie traktują interwencje RF. Postępowanie jest bezpłatne i skuteczne. Możesz też złożyć skargę do KNF lub rozważyć postępowanie przed sądem polubownym przy KNF.",
      },
    ],
  },
  {
    slug: "wypowiedzenie-umowy-abonamentowej",
    title: "Jak wypowiedzieć umowę abonamentową bez kary: wzór pisma 2026",
    description: "Operator, siłownia, platforma streamingowa nie chce rozwiązać umowy lub żąda kary? Masz prawo wypowiedzieć każdą umowę na czas nieokreślony. Art. 365(1) KC i art. 3853 KC po Twojej stronie.",
    date: "2026-04-25",
    readTime: "6 min",
    category: "Wypowiedzenie umowy",
    titleEn: "How to Cancel a Subscription Contract Without Penalty: Template 2026",
    descriptionEn: "Operator, gym, streaming platform refusing to cancel or threatening a penalty? You have the right to terminate any open-ended contract. Art. 365(1) CC and Art. 385(3) CC on your side.",
    categoryEn: "Contract Termination",
    readTimeEn: "6 min",
    faq: [
      {
        q: "Czy można wypowiedzieć umowę abonamentową bez kary?",
        a: "Tak, jeśli umowa jest na czas nieokreślony. Art. 365¹ Kodeksu cywilnego daje Ci prawo do wypowiedzenia każdej umowy bezterminowej z zachowaniem okresu wypowiedzenia. Kara umowna za rezygnację z umowy bezterminowej jest najczęściej nieważna jako klauzula abuzywna (art. 385³ pkt 17 KC).",
      },
      {
        q: "Siłownia żąda kary za wcześniejsze zakończenie umowy. Co zrobić?",
        a: "Sprawdź czy Twoja umowa jest na czas nieokreślony lub czy minął już minimalny okres zobowiązania. Jeśli tak, kara umowna to klauzula niedozwolona z art. 385³ pkt 17 Kodeksu cywilnego. Zakwestionuj ją w piśmie i złóż skargę do UOKiK jeśli siłownia nalicza karę.",
      },
      {
        q: "Operator telefonii nie chce rozwiązać umowy. Jaki jest termin wypowiedzenia?",
        a: "Dla umów telekomunikacyjnych na czas nieokreślony Prawo Komunikacji Elektronicznej przewiduje maksymalnie 30-dniowy okres wypowiedzenia dla konsumentów. Powołaj się na art. 365¹ Kodeksu cywilnego i złóż wypowiedzenie pisemnie.",
      },
      {
        q: "Czy mogę odstąpić od umowy abonamentowej zawartej przez internet bez kary?",
        a: "Tak, jeśli umowę zawarłeś przez internet lub telefon, masz 14 dni na odstąpienie bez podania przyczyny na podstawie art. 27 ustawy o prawach konsumenta. Dotyczy to nowych umów z operatorami, siłowniami i platformami cyfrowymi.",
      },
      {
        q: "Firma podniosła cenę abonamentu. Czy mogę teraz wypowiedzieć umowę bez konsekwencji?",
        a: "Tak. Zmiana cennika lub warunków przez firmę daje Ci prawo do natychmiastowego wypowiedzenia umowy bez żadnych konsekwencji na podstawie art. 384¹ Kodeksu cywilnego. Firma ma obowiązek poinformować Cię o tej możliwości przy zmianie warunków.",
      },
    ],
  },
  {
    slug: "reklamacja-media-expert",
    title: "Reklamacja w Media Expert: jak skutecznie dochodzić praw (2026)",
    description: "Sprzęt z Media Expert się zepsuł? Masz 2 lata na reklamację z tytułu niezgodności z umową — niezależnie od gwarancji producenta. Jak napisać pismo, które sklep musi rozpatrzyć w 14 dniach.",
    date: "2026-04-21",
    readTime: "5 min",
    category: "Elektronika",
    titleEn: "Complaint at Media Expert: How to Enforce Your Rights (2026)",
    descriptionEn: "Equipment from Media Expert broke down? You have 2 years to claim non-conformity — regardless of the manufacturer's warranty. How to write a letter the store must process within 14 days.",
    categoryEn: "Electronics",
    readTimeEn: "5 min",
    faq: [
      { q: "Czy reklamacja w Media Expert wymaga paragonu?", a: "Nie. Dowodem zakupu może być potwierdzenie zamówienia z konta Media Expert, wyciąg z karty czy wydruk z aplikacji. Paragon ułatwia sprawę, ale nie jest wymagany przez przepisy." },
      { q: "Media Expert odsyła mnie do serwisu producenta. Co zrobić?", a: "Możesz odmówić. Masz prawo złożyć reklamację bezpośrednio do sklepu na podstawie art. 43b UPK. Serwis producenta to gwarancja — możesz z niej skorzystać, ale nie musisz rezygnować z praw ustawowych." },
      { q: "Ile czasu ma Media Expert na naprawę lub wymianę?", a: "Ustawa nie podaje konkretnej liczby dni na naprawę, ale musi to być 'rozsądny czas i bez nadmiernych niedogodności'. W praktyce 14–21 dni to akceptowalny czas. Jeśli naprawa przeciąga się bez uzasadnienia, możesz żądać wymiany lub zwrotu." },
      { q: "Kupiłem sprzęt na raty w Media Expert. Czy mogę reklamować?", a: "Tak. Zakup na raty nie ogranicza Twoich praw konsumenckich. Reklamacja trafia do Media Expert jako sprzedawcy, nie do firmy finansującej raty." },
    ],
    faqEn: [
      { q: "Does a complaint at Media Expert require a receipt?", a: "No. Proof of purchase can be an order confirmation from your Media Expert account, a card statement or an app printout. A receipt makes things easier but is not legally required." },
      { q: "Media Expert is sending me to the manufacturer's service centre. What should I do?", a: "You can refuse. You have the right to file a complaint directly with the store under Art. 43b CRA. The manufacturer's service centre relates to the warranty — you may use it, but you do not have to give up your statutory rights." },
      { q: "How long does Media Expert have to repair or replace the item?", a: "The law does not specify an exact number of days, but it must be a 'reasonable time without undue inconvenience'. In practice 14–21 days is acceptable. If the repair drags on without justification, you can demand replacement or a refund." },
      { q: "I bought equipment on an instalment plan. Can I still complain?", a: "Yes. Buying on instalments does not limit your consumer rights. The complaint goes to Media Expert as the seller, not to the financing company." },
    ],
  },
  {
    slug: "reklamacja-rtv-euro-agd",
    title: "Reklamacja w RTV Euro AGD: prawa konsumenta i wzór pisma (2026)",
    description: "Sprzęt AGD lub elektronika z RTV Euro AGD nie działa prawidłowo? Przysługują Ci 2 lata ochrony ustawowej. Dowiedz się jak napisać skuteczną reklamację i czego możesz żądać od sklepu.",
    date: "2026-04-17",
    readTime: "5 min",
    category: "AGD / Elektronika",
    titleEn: "Complaint at RTV Euro AGD: Consumer Rights and Letter Template (2026)",
    descriptionEn: "Home appliance or electronics from RTV Euro AGD not working properly? You have 2 years of statutory protection. Learn how to write an effective complaint and what you can demand from the store.",
    categoryEn: "AGD / Electronics",
    readTimeEn: "5 min",
    faq: [
      { q: "Kupiłem pralkę w RTV Euro AGD rok temu i się zepsuła. Czy mam jeszcze czas na reklamację?", a: "Tak. Masz 2 lata od daty otrzymania towaru. Rok od zakupu to nadal w granicach ustawowego terminu. Złóż reklamację do RTV Euro AGD powołując się na art. 43b ustawy o prawach konsumenta." },
      { q: "RTV Euro AGD żąda ekspertyzy na mój koszt przed przyjęciem reklamacji. Czy to legalne?", a: "Nie. Sklep nie może wymagać od Ciebie pokrycia kosztów ekspertyzy przed rozpatrzeniem reklamacji. Jeśli sklep chce przeprowadzić ekspertyzę, robi to na własny koszt. Ty nie musisz nic płacić z góry." },
      { q: "Czy muszę dostarczyć pralkę do sklepu podczas reklamacji?", a: "Nie. Dla dużego AGD sklep jest zobowiązany zorganizować odbiór wadliwego sprzętu na własny koszt i bez nadmiernych niedogodności dla Ciebie. Nie musisz dowozić pralki ani lodówki do sklepu." },
      { q: "RTV Euro AGD zaproponowało bon na zakupy zamiast zwrotu. Czy muszę przyjąć?", a: "Nie. Jeśli żądasz zwrotu pieniędzy na podstawie art. 43e ust. 1 UPK, sklep musi przelać środki na konto. Bon to dobrowolna propozycja handlowa." },
    ],
    faqEn: [
      { q: "I bought a washing machine at RTV Euro AGD a year ago and it broke. Do I still have time to complain?", a: "Yes. You have 2 years from the date you received the goods. One year from purchase is still within the statutory period. File a complaint with RTV Euro AGD citing Art. 43b of the Consumer Rights Act." },
      { q: "RTV Euro AGD demands an expert assessment at my cost before accepting the complaint. Is this legal?", a: "No. The store cannot require you to cover the cost of an assessment before processing a complaint. If the store wants an assessment, it commissions one at its own expense. You do not pay anything upfront." },
      { q: "Do I have to bring the washing machine to the store during the complaint?", a: "No. For large appliances the store must arrange collection of the faulty item at its own cost and without undue inconvenience to you. You do not have to deliver a washing machine or fridge to the store." },
      { q: "RTV Euro AGD offered a shopping voucher instead of a refund. Do I have to accept it?", a: "No. If you demand a cash refund under Art. 43e §1 CRA, the store must transfer the funds to your account. A voucher is a voluntary commercial offer." },
    ],
  },
  {
    slug: "reklamacja-telefonu",
    title: "Reklamacja telefonu: jak odzyskać pieniądze za wadliwy smartfon (2026)",
    description: "Smartfon się zepsuł, bateria nie wytrzymuje lub wyświetlacz ma defekt? Masz 2 lata na reklamację do sklepu lub operatora. Krok po kroku jak napisać skuteczne pismo i czego żądać.",
    date: "2026-04-13",
    readTime: "6 min",
    category: "Telefon / Operator",
    titleEn: "Phone Complaint: How to Get a Refund for a Faulty Smartphone (2026)",
    descriptionEn: "Smartphone broke, battery drains fast, or display has a defect? You have 2 years to complain to the store or operator. Step by step: how to write an effective letter and what to demand.",
    categoryEn: "Phone / Operator",
    readTimeEn: "6 min",
    faq: [
      { q: "Bateria w telefonie szybko się rozładowuje. Czy to podstawa do reklamacji?", a: "Tak, jeśli degradacja nastąpiła znacznie szybciej niż powinna. Producenci deklarują zazwyczaj 80% pojemności po 500 cyklach ładowania. Jeśli Twoja bateria traci pojemność zdecydowanie szybciej w ciągu roku — masz podstawę do reklamacji z tytułu wady." },
      { q: "Sklep twierdzi że telefon był mokry i dlatego nie przyjmuje reklamacji. Co zrobić?", a: "Sklep musi udowodnić że używałeś telefonu w warunkach niezgodnych z instrukcją. Jeśli telefon jest reklamowany jako wodoodporny (IP67/IP68) a uszkodzył się w normalnych warunkach — masz silną pozycję. Zażądaj pisemnego uzasadnienia odmowy z powołaniem na ekspertyzę." },
      { q: "Kupiłem telefon na abonament. Do kogo składam reklamację?", a: "Do operatora jako sprzedawcy. Operator odpowiada za niezgodność towaru z umową przez 2 lata na podstawie art. 43b UPK, niezależnie od tego, że telefon był dołączony do abonamentu." },
      { q: "Ekran telefonu pęknął sam bez uderzenia. Czy mogę reklamować?", a: "Tak. Samoczynne pękanie ekranu (szczególnie wyświetlaczy OLED) to znany defekt fabryczny. Sklep może próbować twierdzić że doszło do uderzenia, ale musi to udowodnić ekspertyzą. Bez ekspertyzy obowiązuje domniemanie wady z art. 43c ust. 1 UPK." },
    ],
    faqEn: [
      { q: "My phone battery drains quickly. Is this grounds for a complaint?", a: "Yes, if the degradation happened much faster than it should. Manufacturers typically declare 80% capacity after 500 charging cycles. If your battery loses capacity significantly faster within a year — you have grounds for a defect complaint." },
      { q: "The store claims the phone got wet and refuses the complaint. What should I do?", a: "The store must prove you used the phone in conditions contrary to the manual. If the phone is advertised as waterproof (IP67/IP68) and was damaged in normal conditions — you have a strong position. Demand a written rejection citing a technical expert report." },
      { q: "I bought the phone on a mobile plan. Who do I complain to?", a: "To the operator as the seller. The operator is liable for non-conformity for 2 years under Art. 43b CRA, regardless of the phone being bundled with the plan." },
      { q: "My phone screen cracked on its own without impact. Can I complain?", a: "Yes. Spontaneous screen cracking (especially OLED displays) is a known factory defect. The store may claim impact, but must prove it with an expert report. Without a report, the presumption of defect under Art. 43c §1 CRA applies." },
    ],
  },
  {
    slug: "zwrot-od-kuriera",
    title: "Uszkodzona paczka od kuriera: jak uzyskać odszkodowanie (2026)",
    description: "InPost, DPD, DHL uszkodził Twoją paczkę? Masz prawo do odszkodowania z Prawa pocztowego i Prawa przewozowego. Jak sporządzić protokół szkody i złożyć skuteczną reklamację.",
    date: "2026-04-09",
    readTime: "5 min",
    category: "Kurier",
    titleEn: "Damaged Parcel from the Courier: How to Get Compensation (2026)",
    descriptionEn: "InPost, DPD, DHL damaged your parcel? You are entitled to compensation under the Postal Law and Transport Law. How to draw up a damage report and file an effective complaint.",
    categoryEn: "Courier",
    readTimeEn: "5 min",
    faq: [
      { q: "Ile mam czasu na zgłoszenie szkody w paczce od kuriera?", a: "Jeśli szkodę stwierdzono przy odbiorze — sporządź protokół od razu z kurierem. Jeśli odkryłeś szkodę po odbiorze — masz 7 dni na zażądanie protokolarnego ustalenia stanu przesyłki (art. 74 ust. 3 Prawa przewozowego). Po tym terminie dochodzenie roszczenia jest znacząco utrudnione." },
      { q: "Kurier odmówił sporządzenia protokołu szkody. Co zrobić?", a: "Zaznacz własnoręcznie zastrzeżenia na liście przewozowym i sfotografuj. Zrób zdjęcia opakowania i zawartości. Następnie złóż reklamację pisemnie — brak protokołu nie pozbawia Cię prawa do odszkodowania, ale utrudnia postępowanie." },
      { q: "Paczka zaginęła w InPost. Co mi przysługuje?", a: "Odszkodowanie do wysokości zadeklarowanej wartości przesyłki lub do limitu ustawowego. Dla paczek bez deklaracji wartości limit wynika z regulaminu i Prawa pocztowego. Złóż reklamację przez aplikację InPost lub formularz online w ciągu 12 miesięcy od nadania." },
      { q: "Sklep mówi że nie odpowiada za uszkodzenia w transporcie. Czy muszę walczyć z kurierem?", a: "Nie. Jeśli towar dotarł do Ciebie uszkodzony, możesz złożyć reklamację do sklepu (sprzedawca odpowiada za niezgodność towaru z umową) LUB do kuriera. Kwestia rozliczeń między sklepem a kurierem to ich sprawa — nie musisz w tym uczestniczyć." },
    ],
    faqEn: [
      { q: "How long do I have to report damage in a parcel from the courier?", a: "If the damage was found at the time of delivery — draw up a damage report immediately with the courier. If you discovered it after accepting the parcel — you have 7 days to request a formal assessment of the parcel's condition (Art. 74 §3 of the Transport Law). After this period it becomes significantly harder to pursue the claim." },
      { q: "The courier refused to draw up a damage report. What should I do?", a: "Note your objections manually on the waybill and photograph it. Take photos of the packaging and contents. Then file a complaint in writing — the absence of a report does not remove your right to compensation, but it makes the process harder." },
      { q: "My parcel was lost by InPost. What am I entitled to?", a: "Compensation up to the declared value of the shipment or the statutory limit. For parcels without a declared value, the limit follows the terms of service and Postal Law. File a complaint via the InPost app or online form within 12 months of sending." },
      { q: "The store says it is not responsible for damage in transit. Do I have to fight the courier myself?", a: "No. If the goods arrived damaged, you can file a complaint with the store (the seller is liable for non-conformity) OR with the courier. The settlement between the store and the courier is their matter — you do not have to be involved." },
    ],
  },
  {
    slug: "wypowiedzenie-silownia",
    title: "Wypowiedzenie umowy z siłownią: jak odejść bez kary (2026)",
    description: "Siłownia nie chce rozwiązać umowy albo grozi karą za wcześniejsze zakończenie? Kary umowne za wypowiedzenie umowy bezterminowej są nielegalne. Art. 365¹ KC i art. 385³ KC po Twojej stronie.",
    date: "2026-04-05",
    readTime: "5 min",
    category: "Wypowiedzenie umowy",
    titleEn: "Gym Contract Cancellation: How to Leave Without a Penalty (2026)",
    descriptionEn: "The gym refuses to cancel your membership or threatens a penalty for early termination? Cancellation penalties for open-ended contracts are illegal. Art. 365¹ CC and Art. 385³ CC on your side.",
    categoryEn: "Contract Termination",
    readTimeEn: "5 min",
    faq: [
      { q: "Mam umowę z siłownią na czas nieokreślony. Kiedy mogę ją wypowiedzieć?", a: "W każdej chwili z zachowaniem okresu wypowiedzenia podanego w umowie. Jeśli umowa nie podaje okresu wypowiedzenia — zgodnie z art. 365¹ KC możesz wypowiedzieć ją niezwłocznie. Siłownia nie może żądać kary za skorzystanie z ustawowego prawa." },
      { q: "Mam roczną umowę z siłownią i chcę odejść po 4 miesiącach. Co mogę zrobić?", a: "Sprawdź czy siłownia zmieniała cennik lub regulamin od zawarcia umowy — jeśli tak, masz prawo do natychmiastowego wypowiedzenia bez konsekwencji (art. 384¹ KC). Możesz też sprawdzić czy w umowie nie ma klauzul abuzywnych wpisanych do rejestru UOKiK." },
      { q: "Siłownia pobierała opłaty z mojej karty po złożeniu wypowiedzenia. Co zrobić?", a: "Cofnij upoważnienie do pobierania płatności w swoim banku. Wezwij siłownię pisemnie do zwrotu pobranych środków. Jeśli nie reaguje — złóż wniosek o chargeback w banku lub skargę do UOKiK." },
      { q: "Czy zmiana cennika siłowni podczas umowy daje mi prawo do jej wypowiedzenia?", a: "Tak. Jednostronna zmiana warunków umowy lub cennika przez siłownię daje Ci prawo do natychmiastowego wypowiedzenia umowy bez żadnych konsekwencji finansowych na podstawie art. 384¹ Kodeksu cywilnego." },
    ],
    faqEn: [
      { q: "I have an open-ended gym contract. When can I cancel it?", a: "At any time, observing the notice period stated in the contract. If the contract specifies no notice period — under Art. 365¹ CC you can cancel immediately. The gym cannot demand a penalty for exercising a statutory right." },
      { q: "I have a one-year gym contract and want to leave after 4 months. What can I do?", a: "Check whether the gym changed its prices or terms since you signed — if so, you have the right to immediate termination without consequences (Art. 384¹ CC). Also check whether the contract contains abusive clauses listed in the UOKiK register." },
      { q: "The gym kept charging my card after I submitted my cancellation notice. What should I do?", a: "Revoke the direct debit authorisation with your bank. Send the gym a written demand for a refund of the amounts taken. If there is no response — apply for a chargeback with your bank or file a complaint with UOKiK." },
      { q: "Does a price increase by the gym during my contract give me the right to cancel it?", a: "Yes. A unilateral change of contract terms or prices by the gym gives you the right to immediate termination of the contract without any financial consequences under Art. 384¹ of the Civil Code." },
    ],
  },
  {
    slug: "reklamacja-firmy-energetycznej",
    title: "Reklamacja do spółki energetycznej: zawyżony rachunek, odcięcie prądu (2026)",
    description: "Prąd odcięty bez powodu, zawyżony rachunek, błąd licznika? Prawo energetyczne: 14 dni na odpowiedź. Jak złożyć skuteczną reklamację do PGE, Tauron, Enea lub innego sprzedawcy energii.",
    date: "2026-06-03",
    readTime: "5 min",
    category: "Energia",
    titleEn: "Energy Company Complaint: Inflated Bill, Power Cut (2026)",
    descriptionEn: "Power cut without justification, inflated bill, meter error? Energy Law: 14 days to respond. How to file an effective complaint with your energy supplier.",
    categoryEn: "Energy",
    readTimeEn: "5 min",
    faq: [
      { q: "Ile dni ma spółka energetyczna na odpowiedź na reklamację?", a: "14 dni kalendarzowych od złożenia reklamacji. Jeśli wymagane jest postępowanie wyjaśniające — 30 dni, ale spółka musi Cię o tym poinformować. Brak odpowiedzi w terminie = reklamacja uznana." },
      { q: "Rachunek za prąd jest znacznie wyższy niż zwykle. Co zrobić?", a: "Zażądaj pisemnie sprawdzenia licznika. Jeśli licznik jest wadliwy — spółka pokrywa koszty weryfikacji i koryguje rachunki za cały okres wadliwego działania. Równocześnie złóż reklamację wstrzymując płatność spornej kwoty." },
      { q: "Firma energetyczna odcięła prąd. Czy miała prawo?", a: "Tylko jeśli wcześniej wysłała pisemne wezwanie do zapłaty z minimum 14-dniowym terminem i powiadomiła Cię o zamiarze odcięcia z minimum 7-dniowym wyprzedzeniem (art. 6c Prawa energetycznego). Bezprawne odcięcie uprawnia do odszkodowania." },
      { q: "Gdzie złożyć skargę jeśli spółka energetyczna nie reaguje?", a: "Do Prezesa URE (ure.gov.pl) — może nakazać spółce działanie. Możesz też skorzystać z bezpłatnej mediacji przy Prezesie URE lub zgłosić się do Rzecznika Praw Konsumenta w swoim powiecie." },
    ],
  },
  {
    slug: "reklamacja-operatora",
    title: "Reklamacja do operatora: telefon, internet, TV — prawa i wzór pisma (2026)",
    description: "Błędny rachunek, przerwa w usłudze, kara za wypowiedzenie, za wolny internet? Operator ma 30 dni na odpowiedź (art. 306 PKE). Brak odpowiedzi = reklamacja uznana. Jak napisać skuteczne pismo.",
    date: "2026-06-07",
    readTime: "5 min",
    category: "Telefon / Operator",
    titleEn: "Telecom Complaint: Phone, Internet, TV — Rights and Letter Template (2026)",
    descriptionEn: "Wrong bill, service outage, cancellation penalty, slow internet? Operator has 30 days to respond (Art. 306 PKE). No reply = complaint accepted by law. How to write an effective letter.",
    categoryEn: "Phone / Operator",
    readTimeEn: "5 min",
    faq: [
      { q: "Ile dni ma operator na odpowiedź na reklamację?", a: "Przy reklamacjach o błędny rachunek lub niezgodność z umową — 14 dni od dnia otrzymania (art. 7a ustawy o prawach konsumenta). Przy skargach na decyzje operatora — 30 dni (art. 306 PKE). W obu przypadkach brak odpowiedzi w terminie = reklamacja uznana za zasadną." },
      { q: "Operator zmienił mi cennik i chce kary za wypowiedzenie. Czy musi tak być?", a: "Nie. Zmiana cennika lub warunków umowy daje Ci prawo do wypowiedzenia umowy bez żadnych kar w terminie 30 dni od powiadomienia (art. 302 PKE). Operator ma obowiązek poinformować Cię o tej możliwości przy każdej zmianie warunków." },
      { q: "Internet jest znacznie wolniejszy niż w umowie. Co mogę zrobić?", a: "Przeprowadź test prędkości (np. speedtest.net) i zachowaj wynik z datą i godziną. Złóż reklamację z żądaniem proporcjonalnego obniżenia rachunku za okres niedostępności lub obniżonej jakości usługi (art. 308 PKE). Dołącz wyniki testów jako dowód." },
      { q: "Gdzie złożyć skargę jeśli operator nie reaguje na reklamację?", a: "Do Prezesa UKE (urzad.uke.gov.pl) — może wszcząć postępowanie wyjaśniające. Możesz też skorzystać z bezpłatnego Stałego Polubownego Sądu Konsumenckiego przy UKE lub zgłosić się do Rzecznika Praw Konsumenta w swoim powiecie." },
    ],
  },
];

export function getPost(slug: string): Post | undefined {
  return POSTS.find(p => p.slug === slug);
}

